// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/k8s_policy.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Metadata } from "./metadata_pb";
import { file_kessel_inventory_v1beta1_resources_metadata } from "./metadata_pb";
import type { K8sPolicyDetail } from "./k8s_policy_detail_pb";
import { file_kessel_inventory_v1beta1_resources_k8s_policy_detail } from "./k8s_policy_detail_pb";
import type { ReporterData } from "./reporter_data_pb";
import { file_kessel_inventory_v1beta1_resources_reporter_data } from "./reporter_data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/k8s_policy.proto.
 */
export const file_kessel_inventory_v1beta1_resources_k8s_policy: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjNrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL2s4c19wb2xpY3kucHJvdG8SImtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMilAIKCUs4c1BvbGljeRI+CghtZXRhZGF0YRgBIAEoCzIsLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuTWV0YWRhdGESYQoNcmVwb3J0ZXJfZGF0YRjI0Pp0IAEoCzIwLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuUmVwb3J0ZXJEYXRhQga6SAPIAQFSDXJlcG9ydGVyX2RhdGESZAoNcmVzb3VyY2VfZGF0YRjKx4EBIAEoCzIzLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuSzhzUG9saWN5RGV0YWlsQga6SAPIAQFSDXJlc291cmNlX2RhdGFClgEKMm9yZy5wcm9qZWN0X2tlc3NlbC5hcGkuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzQg5LOHNQb2xpY3lQcm90b1ABWk5naXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXNiBnByb3RvMw",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta1_resources_metadata,
      file_kessel_inventory_v1beta1_resources_k8s_policy_detail,
      file_kessel_inventory_v1beta1_resources_reporter_data,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.K8sPolicy
 */
export type K8sPolicy =
  Message<"kessel.inventory.v1beta1.resources.K8sPolicy"> & {
    /**
     * Metadata about this resource
     *
     * @generated from field: kessel.inventory.v1beta1.resources.Metadata metadata = 1;
     */
    metadata?: Metadata;

    /**
     * Write only reporter specific data
     *
     * @generated from field: kessel.inventory.v1beta1.resources.ReporterData reporter_data = 245278792 [json_name = "reporter_data"];
     */
    reporterData?: ReporterData;

    /**
     * @generated from field: kessel.inventory.v1beta1.resources.K8sPolicyDetail resource_data = 2122698 [json_name = "resource_data"];
     */
    resourceData?: K8sPolicyDetail;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.K8sPolicy.
 * Use `create(K8sPolicySchema)` to create a new message.
 */
export const K8sPolicySchema: GenMessage<K8sPolicy> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_policy, 0);
