// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/k8s_policies_service.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../google/api/annotations_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { K8sPolicy } from "./k8s_policy_pb";
import { file_kessel_inventory_v1beta1_resources_k8s_policy } from "./k8s_policy_pb";
import type { ReporterData } from "./reporter_data_pb";
import { file_kessel_inventory_v1beta1_resources_reporter_data } from "./reporter_data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/k8s_policies_service.proto.
 */
export const file_kessel_inventory_v1beta1_resources_k8s_policies_service: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Cj1rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL2s4c19wb2xpY2llc19zZXJ2aWNlLnByb3RvEiJrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzIm8KFkNyZWF0ZUs4c1BvbGljeVJlcXVlc3QSVQoKazhzX3BvbGljeRgBIAEoCzItLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuSzhzUG9saWN5Qga6SAPIAQFSCms4c19wb2xpY3kiGQoXQ3JlYXRlSzhzUG9saWN5UmVzcG9uc2UibwoWVXBkYXRlSzhzUG9saWN5UmVxdWVzdBJVCgprOHNfcG9saWN5GAEgASgLMi0ua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5LOHNQb2xpY3lCBrpIA8gBAVIKazhzX3BvbGljeSIZChdVcGRhdGVLOHNQb2xpY3lSZXNwb25zZSJ4ChZEZWxldGVLOHNQb2xpY3lSZXF1ZXN0El4KDXJlcG9ydGVyX2RhdGEYASABKAsyMC5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzLlJlcG9ydGVyRGF0YUIGukgDyAEBUg1yZXBvcnRlcl9kYXRhIhkKF0RlbGV0ZUs4c1BvbGljeVJlc3BvbnNlMu0EChZLZXNzZWxLOHNQb2xpY3lTZXJ2aWNlEsQBCg9DcmVhdGVLOHNQb2xpY3kSOi5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzLkNyZWF0ZUs4c1BvbGljeVJlcXVlc3QaOy5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzLkNyZWF0ZUs4c1BvbGljeVJlc3BvbnNlIjiC0+STAjI6ASoiLS9hcGkvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL2s4cy1wb2xpY2llcxLEAQoPVXBkYXRlSzhzUG9saWN5Ejoua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5VcGRhdGVLOHNQb2xpY3lSZXF1ZXN0Gjsua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5VcGRhdGVLOHNQb2xpY3lSZXNwb25zZSI4gtPkkwIyOgEqGi0vYXBpL2ludmVudG9yeS92MWJldGExL3Jlc291cmNlcy9rOHMtcG9saWNpZXMSxAEKD0RlbGV0ZUs4c1BvbGljeRI6Lmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuRGVsZXRlSzhzUG9saWN5UmVxdWVzdBo7Lmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuRGVsZXRlSzhzUG9saWN5UmVzcG9uc2UiOILT5JMCMjoBKiotL2FwaS9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXMvazhzLXBvbGljaWVzQoYBCjJvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGExLnJlc291cmNlc1ABWk5naXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXNiBnByb3RvMw",
    [
      file_google_api_annotations,
      file_buf_validate_validate,
      file_kessel_inventory_v1beta1_resources_k8s_policy,
      file_kessel_inventory_v1beta1_resources_reporter_data,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.CreateK8sPolicyRequest
 */
export type CreateK8sPolicyRequest =
  Message<"kessel.inventory.v1beta1.resources.CreateK8sPolicyRequest"> & {
    /**
     * The policy to create in Kessel Asset Inventory
     *
     * @generated from field: kessel.inventory.v1beta1.resources.K8sPolicy k8s_policy = 1 [json_name = "k8s_policy"];
     */
    k8sPolicy?: K8sPolicy;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.CreateK8sPolicyRequest.
 * Use `create(CreateK8sPolicyRequestSchema)` to create a new message.
 */
export const CreateK8sPolicyRequestSchema: GenMessage<CreateK8sPolicyRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_policies_service, 0);

/**
 * @generated from message kessel.inventory.v1beta1.resources.CreateK8sPolicyResponse
 */
export type CreateK8sPolicyResponse =
  Message<"kessel.inventory.v1beta1.resources.CreateK8sPolicyResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta1.resources.CreateK8sPolicyResponse.
 * Use `create(CreateK8sPolicyResponseSchema)` to create a new message.
 */
export const CreateK8sPolicyResponseSchema: GenMessage<CreateK8sPolicyResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_policies_service, 1);

/**
 * @generated from message kessel.inventory.v1beta1.resources.UpdateK8sPolicyRequest
 */
export type UpdateK8sPolicyRequest =
  Message<"kessel.inventory.v1beta1.resources.UpdateK8sPolicyRequest"> & {
    /**
     * The resource to be updated will be defined by
     * \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
     * from the request body.
     *
     * @generated from field: kessel.inventory.v1beta1.resources.K8sPolicy k8s_policy = 1 [json_name = "k8s_policy"];
     */
    k8sPolicy?: K8sPolicy;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.UpdateK8sPolicyRequest.
 * Use `create(UpdateK8sPolicyRequestSchema)` to create a new message.
 */
export const UpdateK8sPolicyRequestSchema: GenMessage<UpdateK8sPolicyRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_policies_service, 2);

/**
 * @generated from message kessel.inventory.v1beta1.resources.UpdateK8sPolicyResponse
 */
export type UpdateK8sPolicyResponse =
  Message<"kessel.inventory.v1beta1.resources.UpdateK8sPolicyResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta1.resources.UpdateK8sPolicyResponse.
 * Use `create(UpdateK8sPolicyResponseSchema)` to create a new message.
 */
export const UpdateK8sPolicyResponseSchema: GenMessage<UpdateK8sPolicyResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_policies_service, 3);

/**
 * @generated from message kessel.inventory.v1beta1.resources.DeleteK8sPolicyRequest
 */
export type DeleteK8sPolicyRequest =
  Message<"kessel.inventory.v1beta1.resources.DeleteK8sPolicyRequest"> & {
    /**
     * The resource to be deleted will be defined by
     * \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
     * from the request body.
     *
     * @generated from field: kessel.inventory.v1beta1.resources.ReporterData reporter_data = 1 [json_name = "reporter_data"];
     */
    reporterData?: ReporterData;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.DeleteK8sPolicyRequest.
 * Use `create(DeleteK8sPolicyRequestSchema)` to create a new message.
 */
export const DeleteK8sPolicyRequestSchema: GenMessage<DeleteK8sPolicyRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_policies_service, 4);

/**
 * @generated from message kessel.inventory.v1beta1.resources.DeleteK8sPolicyResponse
 */
export type DeleteK8sPolicyResponse =
  Message<"kessel.inventory.v1beta1.resources.DeleteK8sPolicyResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta1.resources.DeleteK8sPolicyResponse.
 * Use `create(DeleteK8sPolicyResponseSchema)` to create a new message.
 */
export const DeleteK8sPolicyResponseSchema: GenMessage<DeleteK8sPolicyResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_policies_service, 5);

/**
 * @generated from service kessel.inventory.v1beta1.resources.KesselK8sPolicyService
 */
export const KesselK8sPolicyService: GenService<{
  /**
   * @generated from rpc kessel.inventory.v1beta1.resources.KesselK8sPolicyService.CreateK8sPolicy
   */
  createK8sPolicy: {
    methodKind: "unary";
    input: typeof CreateK8sPolicyRequestSchema;
    output: typeof CreateK8sPolicyResponseSchema;
  };
  /**
   * @generated from rpc kessel.inventory.v1beta1.resources.KesselK8sPolicyService.UpdateK8sPolicy
   */
  updateK8sPolicy: {
    methodKind: "unary";
    input: typeof UpdateK8sPolicyRequestSchema;
    output: typeof UpdateK8sPolicyResponseSchema;
  };
  /**
   * @generated from rpc kessel.inventory.v1beta1.resources.KesselK8sPolicyService.DeleteK8sPolicy
   */
  deleteK8sPolicy: {
    methodKind: "unary";
    input: typeof DeleteK8sPolicyRequestSchema;
    output: typeof DeleteK8sPolicyResponseSchema;
  };
}> =
  /*@__PURE__*/
  serviceDesc(file_kessel_inventory_v1beta1_resources_k8s_policies_service, 0);
