// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/k8s_cluster_detail_nodes_inner.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { ResourceLabel } from "./resource_label_pb";
import { file_kessel_inventory_v1beta1_resources_resource_label } from "./resource_label_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/k8s_cluster_detail_nodes_inner.proto.
 */
export const file_kessel_inventory_v1beta1_resources_k8s_cluster_detail_nodes_inner: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CkdrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL2s4c19jbHVzdGVyX2RldGFpbF9ub2Rlc19pbm5lci5wcm90bxIia2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcyK9AQoaSzhzQ2x1c3RlckRldGFpbE5vZGVzSW5uZXISGAoEbmFtZRiL9c0BIAEoCUIHukgEcgIQARIWCgNjcHUYqIMGIAEoCUIHukgEcgIQARIaCgZtZW1vcnkYgYb1ASABKAlCB7pIBHICEAESUQoGbGFiZWxzGIPAvhEgAygLMjEua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5SZXNvdXJjZUxhYmVsQgu6SAiSAQUiA8gBAUKnAQoyb3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXNCH0s4c0NsdXN0ZXJEZXRhaWxOb2Rlc0lubmVyUHJvdG9QAVpOZ2l0aHViLmNvbS9wcm9qZWN0LWtlc3NlbC9pbnZlbnRvcnktYXBpL2FwaS9rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzYgZwcm90bzM",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta1_resources_resource_label,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner
 */
export type K8sClusterDetailNodesInner =
  Message<"kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner"> & {
    /**
     * The name of the node (this can contain private info)
     *
     * @generated from field: string name = 3373707;
     */
    name: string;

    /**
     * CPU Capacity of the node defined in CPU units, e.g. \"0.5\"
     *
     * @generated from field: string cpu = 98728;
     */
    cpu: string;

    /**
     * Memory Capacity of the node defined as MiB, e.g. \"50Mi\"
     *
     * @generated from field: string memory = 4014849;
     */
    memory: string;

    /**
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     *
     * @generated from field: repeated kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587;
     */
    labels: ResourceLabel[];
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner.
 * Use `create(K8sClusterDetailNodesInnerSchema)` to create a new message.
 */
export const K8sClusterDetailNodesInnerSchema: GenMessage<K8sClusterDetailNodesInner> =
  /*@__PURE__*/
  messageDesc(
    file_kessel_inventory_v1beta1_resources_k8s_cluster_detail_nodes_inner,
    0,
  );
