// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/k8s_policy_detail.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type {
  GenEnum,
  GenFile,
  GenMessage,
} from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/k8s_policy_detail.proto.
 */
export const file_kessel_inventory_v1beta1_resources_k8s_policy_detail: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjprZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL2s4c19wb2xpY3lfZGV0YWlsLnByb3RvEiJrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzIuwBCg9LOHNQb2xpY3lEZXRhaWwSFAoIZGlzYWJsZWQY/fSYgQEgASgIElwKCHNldmVyaXR5GICm9MABIAEoDjI8Lmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuSzhzUG9saWN5RGV0YWlsLlNldmVyaXR5Qgi6SAWCAQIQASJlCghTZXZlcml0eRIYChRTRVZFUklUWV9VTlNQRUNJRklFRBAAEhIKDlNFVkVSSVRZX09USEVSEAESBwoDTE9XEAISCgoGTUVESVVNEAMSCAoESElHSBAEEgwKCENSSVRJQ0FMEAVCnAEKMm9yZy5wcm9qZWN0X2tlc3NlbC5hcGkuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzQhRLOHNQb2xpY3lEZXRhaWxQcm90b1ABWk5naXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXNiBnByb3RvMw",
    [file_buf_validate_validate],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.K8sPolicyDetail
 */
export type K8sPolicyDetail =
  Message<"kessel.inventory.v1beta1.resources.K8sPolicyDetail"> & {
    /**
     * Defines if the policy is currently enabled or disabled across all targets
     *
     * @generated from field: bool disabled = 270940797;
     */
    disabled: boolean;

    /**
     * @generated from field: kessel.inventory.v1beta1.resources.K8sPolicyDetail.Severity severity = 404558592;
     */
    severity: K8sPolicyDetail_Severity;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.K8sPolicyDetail.
 * Use `create(K8sPolicyDetailSchema)` to create a new message.
 */
export const K8sPolicyDetailSchema: GenMessage<K8sPolicyDetail> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_policy_detail, 0);

/**
 * The kind of policy
 *
 * @generated from enum kessel.inventory.v1beta1.resources.K8sPolicyDetail.Severity
 */
export enum K8sPolicyDetail_Severity {
  /**
   * @generated from enum value: SEVERITY_UNSPECIFIED = 0;
   */
  SEVERITY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: SEVERITY_OTHER = 1;
   */
  SEVERITY_OTHER = 1,

  /**
   * @generated from enum value: LOW = 2;
   */
  LOW = 2,

  /**
   * @generated from enum value: MEDIUM = 3;
   */
  MEDIUM = 3,

  /**
   * @generated from enum value: HIGH = 4;
   */
  HIGH = 4,

  /**
   * @generated from enum value: CRITICAL = 5;
   */
  CRITICAL = 5,
}

/**
 * Describes the enum kessel.inventory.v1beta1.resources.K8sPolicyDetail.Severity.
 */
export const K8sPolicyDetail_SeveritySchema: GenEnum<K8sPolicyDetail_Severity> =
  /*@__PURE__*/
  enumDesc(file_kessel_inventory_v1beta1_resources_k8s_policy_detail, 0, 0);
