// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/k8s_clusters_service.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../google/api/annotations_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { K8sCluster } from "./k8s_cluster_pb";
import { file_kessel_inventory_v1beta1_resources_k8s_cluster } from "./k8s_cluster_pb";
import type { ReporterData } from "./reporter_data_pb";
import { file_kessel_inventory_v1beta1_resources_reporter_data } from "./reporter_data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/k8s_clusters_service.proto.
 */
export const file_kessel_inventory_v1beta1_resources_k8s_clusters_service: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Cj1rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL2s4c19jbHVzdGVyc19zZXJ2aWNlLnByb3RvEiJrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzImsKF0NyZWF0ZUs4c0NsdXN0ZXJSZXF1ZXN0ElAKC2s4c19jbHVzdGVyGAEgASgLMi4ua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5LOHNDbHVzdGVyUgtrOHNfY2x1c3RlciIaChhDcmVhdGVLOHNDbHVzdGVyUmVzcG9uc2UiawoXVXBkYXRlSzhzQ2x1c3RlclJlcXVlc3QSUAoLazhzX2NsdXN0ZXIYASABKAsyLi5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzLks4c0NsdXN0ZXJSC2s4c19jbHVzdGVyIhoKGFVwZGF0ZUs4c0NsdXN0ZXJSZXNwb25zZSJ5ChdEZWxldGVLOHNDbHVzdGVyUmVxdWVzdBJeCg1yZXBvcnRlcl9kYXRhGAEgASgLMjAua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5SZXBvcnRlckRhdGFCBrpIA8gBAVINcmVwb3J0ZXJfZGF0YSIaChhEZWxldGVLOHNDbHVzdGVyUmVzcG9uc2Uy9wQKF0tlc3NlbEs4c0NsdXN0ZXJTZXJ2aWNlEscBChBDcmVhdGVLOHNDbHVzdGVyEjsua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5DcmVhdGVLOHNDbHVzdGVyUmVxdWVzdBo8Lmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuQ3JlYXRlSzhzQ2x1c3RlclJlc3BvbnNlIjiC0+STAjI6ASoiLS9hcGkvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL2s4cy1jbHVzdGVycxLHAQoQVXBkYXRlSzhzQ2x1c3RlchI7Lmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuVXBkYXRlSzhzQ2x1c3RlclJlcXVlc3QaPC5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzLlVwZGF0ZUs4c0NsdXN0ZXJSZXNwb25zZSI4gtPkkwIyOgEqGi0vYXBpL2ludmVudG9yeS92MWJldGExL3Jlc291cmNlcy9rOHMtY2x1c3RlcnMSxwEKEERlbGV0ZUs4c0NsdXN0ZXISOy5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzLkRlbGV0ZUs4c0NsdXN0ZXJSZXF1ZXN0Gjwua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5EZWxldGVLOHNDbHVzdGVyUmVzcG9uc2UiOILT5JMCMjoBKiotL2FwaS9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXMvazhzLWNsdXN0ZXJzQoYBCjJvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGExLnJlc291cmNlc1ABWk5naXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXNiBnByb3RvMw",
    [
      file_google_api_annotations,
      file_buf_validate_validate,
      file_kessel_inventory_v1beta1_resources_k8s_cluster,
      file_kessel_inventory_v1beta1_resources_reporter_data,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.CreateK8sClusterRequest
 */
export type CreateK8sClusterRequest =
  Message<"kessel.inventory.v1beta1.resources.CreateK8sClusterRequest"> & {
    /**
     * The k8s cluster to create in Kessel Asset Inventory
     *
     * @generated from field: kessel.inventory.v1beta1.resources.K8sCluster k8s_cluster = 1 [json_name = "k8s_cluster"];
     */
    k8sCluster?: K8sCluster;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.CreateK8sClusterRequest.
 * Use `create(CreateK8sClusterRequestSchema)` to create a new message.
 */
export const CreateK8sClusterRequestSchema: GenMessage<CreateK8sClusterRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_clusters_service, 0);

/**
 * @generated from message kessel.inventory.v1beta1.resources.CreateK8sClusterResponse
 */
export type CreateK8sClusterResponse =
  Message<"kessel.inventory.v1beta1.resources.CreateK8sClusterResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta1.resources.CreateK8sClusterResponse.
 * Use `create(CreateK8sClusterResponseSchema)` to create a new message.
 */
export const CreateK8sClusterResponseSchema: GenMessage<CreateK8sClusterResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_clusters_service, 1);

/**
 * @generated from message kessel.inventory.v1beta1.resources.UpdateK8sClusterRequest
 */
export type UpdateK8sClusterRequest =
  Message<"kessel.inventory.v1beta1.resources.UpdateK8sClusterRequest"> & {
    /**
     * The resource to be updated will be defined by
     * \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
     * from the request body.
     *
     * @generated from field: kessel.inventory.v1beta1.resources.K8sCluster k8s_cluster = 1 [json_name = "k8s_cluster"];
     */
    k8sCluster?: K8sCluster;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.UpdateK8sClusterRequest.
 * Use `create(UpdateK8sClusterRequestSchema)` to create a new message.
 */
export const UpdateK8sClusterRequestSchema: GenMessage<UpdateK8sClusterRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_clusters_service, 2);

/**
 * @generated from message kessel.inventory.v1beta1.resources.UpdateK8sClusterResponse
 */
export type UpdateK8sClusterResponse =
  Message<"kessel.inventory.v1beta1.resources.UpdateK8sClusterResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta1.resources.UpdateK8sClusterResponse.
 * Use `create(UpdateK8sClusterResponseSchema)` to create a new message.
 */
export const UpdateK8sClusterResponseSchema: GenMessage<UpdateK8sClusterResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_clusters_service, 3);

/**
 * @generated from message kessel.inventory.v1beta1.resources.DeleteK8sClusterRequest
 */
export type DeleteK8sClusterRequest =
  Message<"kessel.inventory.v1beta1.resources.DeleteK8sClusterRequest"> & {
    /**
     * The resource to be deleted will be defined by
     * \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
     * from the request body.
     *
     * @generated from field: kessel.inventory.v1beta1.resources.ReporterData reporter_data = 1 [json_name = "reporter_data"];
     */
    reporterData?: ReporterData;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.DeleteK8sClusterRequest.
 * Use `create(DeleteK8sClusterRequestSchema)` to create a new message.
 */
export const DeleteK8sClusterRequestSchema: GenMessage<DeleteK8sClusterRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_clusters_service, 4);

/**
 * @generated from message kessel.inventory.v1beta1.resources.DeleteK8sClusterResponse
 */
export type DeleteK8sClusterResponse =
  Message<"kessel.inventory.v1beta1.resources.DeleteK8sClusterResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta1.resources.DeleteK8sClusterResponse.
 * Use `create(DeleteK8sClusterResponseSchema)` to create a new message.
 */
export const DeleteK8sClusterResponseSchema: GenMessage<DeleteK8sClusterResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_clusters_service, 5);

/**
 * @generated from service kessel.inventory.v1beta1.resources.KesselK8sClusterService
 */
export const KesselK8sClusterService: GenService<{
  /**
   * @generated from rpc kessel.inventory.v1beta1.resources.KesselK8sClusterService.CreateK8sCluster
   */
  createK8sCluster: {
    methodKind: "unary";
    input: typeof CreateK8sClusterRequestSchema;
    output: typeof CreateK8sClusterResponseSchema;
  };
  /**
   * @generated from rpc kessel.inventory.v1beta1.resources.KesselK8sClusterService.UpdateK8sCluster
   */
  updateK8sCluster: {
    methodKind: "unary";
    input: typeof UpdateK8sClusterRequestSchema;
    output: typeof UpdateK8sClusterResponseSchema;
  };
  /**
   * @generated from rpc kessel.inventory.v1beta1.resources.KesselK8sClusterService.DeleteK8sCluster
   */
  deleteK8sCluster: {
    methodKind: "unary";
    input: typeof DeleteK8sClusterRequestSchema;
    output: typeof DeleteK8sClusterResponseSchema;
  };
}> =
  /*@__PURE__*/
  serviceDesc(file_kessel_inventory_v1beta1_resources_k8s_clusters_service, 0);
