// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/k8s_cluster.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { K8sClusterDetail } from "./k8s_cluster_detail_pb";
import { file_kessel_inventory_v1beta1_resources_k8s_cluster_detail } from "./k8s_cluster_detail_pb";
import type { Metadata } from "./metadata_pb";
import { file_kessel_inventory_v1beta1_resources_metadata } from "./metadata_pb";
import type { ReporterData } from "./reporter_data_pb";
import { file_kessel_inventory_v1beta1_resources_reporter_data } from "./reporter_data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/k8s_cluster.proto.
 */
export const file_kessel_inventory_v1beta1_resources_k8s_cluster: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjRrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL2s4c19jbHVzdGVyLnByb3RvEiJrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzIpYCCgpLOHNDbHVzdGVyEj4KCG1ldGFkYXRhGAEgASgLMiwua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5NZXRhZGF0YRJhCg1yZXBvcnRlcl9kYXRhGMjQ+nQgASgLMjAua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5SZXBvcnRlckRhdGFCBrpIA8gBAVINcmVwb3J0ZXJfZGF0YRJlCg1yZXNvdXJjZV9kYXRhGMrHgQEgASgLMjQua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5LOHNDbHVzdGVyRGV0YWlsQga6SAPIAQFSDXJlc291cmNlX2RhdGFClwEKMm9yZy5wcm9qZWN0X2tlc3NlbC5hcGkuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzQg9LOHNDbHVzdGVyUHJvdG9QAVpOZ2l0aHViLmNvbS9wcm9qZWN0LWtlc3NlbC9pbnZlbnRvcnktYXBpL2FwaS9rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzYgZwcm90bzM",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta1_resources_k8s_cluster_detail,
      file_kessel_inventory_v1beta1_resources_metadata,
      file_kessel_inventory_v1beta1_resources_reporter_data,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.K8sCluster
 */
export type K8sCluster =
  Message<"kessel.inventory.v1beta1.resources.K8sCluster"> & {
    /**
     * Metadata about this resource
     *
     * @generated from field: kessel.inventory.v1beta1.resources.Metadata metadata = 1;
     */
    metadata?: Metadata;

    /**
     * Write only reporter specific data
     *
     * @generated from field: kessel.inventory.v1beta1.resources.ReporterData reporter_data = 245278792 [json_name = "reporter_data"];
     */
    reporterData?: ReporterData;

    /**
     * @generated from field: kessel.inventory.v1beta1.resources.K8sClusterDetail resource_data = 2122698 [json_name = "resource_data"];
     */
    resourceData?: K8sClusterDetail;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.K8sCluster.
 * Use `create(K8sClusterSchema)` to create a new message.
 */
export const K8sClusterSchema: GenMessage<K8sCluster> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_k8s_cluster, 0);
