// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/metadata.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../../google/api/field_behavior_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { ResourceLabel } from "./resource_label_pb";
import { file_kessel_inventory_v1beta1_resources_resource_label } from "./resource_label_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/metadata.proto.
 */
export const file_kessel_inventory_v1beta1_resources_metadata: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjFrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL21ldGFkYXRhLnByb3RvEiJrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzIpUDCghNZXRhZGF0YRIQCgJpZBibGiABKAlCA+BBAxItCg1yZXNvdXJjZV90eXBlGMy5j9MBIAEoCUID4EEDUg1yZXNvdXJjZV90eXBlEkAKCmNyZWF0ZWRfYXQYyBogASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDUgpjcmVhdGVkX2F0EkAKCnVwZGF0ZWRfYXQYyRogASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDUgp1cGRhdGVkX2F0EkAKCmRlbGV0ZWRfYXQYyhogASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDUgpkZWxldGVkX2F0EhcKBm9yZ19pZBisGyABKAlSBm9yZ19pZBIjCgx3b3Jrc3BhY2VfaWQYrRsgASgJUgx3b3Jrc3BhY2VfaWQSRAoGbGFiZWxzGJno2AEgAygLMjEua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5SZXNvdXJjZUxhYmVsQoYBCjJvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGExLnJlc291cmNlc1ABWk5naXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXNiBnByb3RvMw",
    [
      file_google_api_field_behavior,
      file_google_protobuf_timestamp,
      file_kessel_inventory_v1beta1_resources_resource_label,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.Metadata
 */
export type Metadata =
  Message<"kessel.inventory.v1beta1.resources.Metadata"> & {
    /**
     * Kessel Asset Inventory generated identifier.
     *
     * @generated from field: string id = 3355;
     */
    id: string;

    /**
     * The type of the Resource
     *
     * @generated from field: string resource_type = 442752204 [json_name = "resource_type"];
     */
    resourceType: string;

    /**
     * Date and time when the inventory item was first reported.
     *
     * @generated from field: google.protobuf.Timestamp created_at = 3400 [json_name = "created_at"];
     */
    createdAt?: Timestamp;

    /**
     * Date and time when the inventory item was last updated.
     *
     * @generated from field: google.protobuf.Timestamp updated_at = 3401 [json_name = "updated_at"];
     */
    updatedAt?: Timestamp;

    /**
     * Date and time when the inventory item was deleted.
     *
     * @generated from field: google.protobuf.Timestamp deleted_at = 3402 [json_name = "deleted_at"];
     */
    deletedAt?: Timestamp;

    /**
     * The org id in which this resource is a member for access control.  A
     * resource can only be a member of one org.
     *
     * @generated from field: string org_id = 3500 [json_name = "org_id"];
     */
    orgId: string;

    /**
     * The workspace id in which this resource is a member for access control.  A
     * resource can only be a member of one workspace.
     *
     * @generated from field: string workspace_id = 3501 [json_name = "workspace_id"];
     */
    workspaceId: string;

    /**
     * @generated from field: repeated kessel.inventory.v1beta1.resources.ResourceLabel labels = 3552281;
     */
    labels: ResourceLabel[];
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_metadata, 0);
