// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/notifications_integration.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../../google/api/field_behavior_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Metadata } from "./metadata_pb";
import { file_kessel_inventory_v1beta1_resources_metadata } from "./metadata_pb";
import type { ReporterData } from "./reporter_data_pb";
import { file_kessel_inventory_v1beta1_resources_reporter_data } from "./reporter_data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/notifications_integration.proto.
 */
export const file_kessel_inventory_v1beta1_resources_notifications_integration: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CkJrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL25vdGlmaWNhdGlvbnNfaW50ZWdyYXRpb24ucHJvdG8SImtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMiwAEKGE5vdGlmaWNhdGlvbnNJbnRlZ3JhdGlvbhI+CghtZXRhZGF0YRgBIAEoCzIsLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuTWV0YWRhdGESZAoNcmVwb3J0ZXJfZGF0YRjI0Pp0IAEoCzIwLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuUmVwb3J0ZXJEYXRhQgngQQS6SAPIAQFSDXJlcG9ydGVyX2RhdGFChgEKMm9yZy5wcm9qZWN0X2tlc3NlbC5hcGkuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzUAFaTmdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGExL3Jlc291cmNlc2IGcHJvdG8z",
    [
      file_google_api_field_behavior,
      file_buf_validate_validate,
      file_kessel_inventory_v1beta1_resources_metadata,
      file_kessel_inventory_v1beta1_resources_reporter_data,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.NotificationsIntegration
 */
export type NotificationsIntegration =
  Message<"kessel.inventory.v1beta1.resources.NotificationsIntegration"> & {
    /**
     * Metadata about this resource
     *
     * @generated from field: kessel.inventory.v1beta1.resources.Metadata metadata = 1;
     */
    metadata?: Metadata;

    /**
     * Write only reporter specific data
     *
     * @generated from field: kessel.inventory.v1beta1.resources.ReporterData reporter_data = 245278792 [json_name = "reporter_data"];
     */
    reporterData?: ReporterData;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.NotificationsIntegration.
 * Use `create(NotificationsIntegrationSchema)` to create a new message.
 */
export const NotificationsIntegrationSchema: GenMessage<NotificationsIntegration> =
  /*@__PURE__*/
  messageDesc(
    file_kessel_inventory_v1beta1_resources_notifications_integration,
    0,
  );
