// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/reporter_data.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type {
  GenEnum,
  GenFile,
  GenMessage,
} from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../../google/api/field_behavior_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/reporter_data.proto.
 */
export const file_kessel_inventory_v1beta1_resources_reporter_data: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjZrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL3JlcG9ydGVyX2RhdGEucHJvdG8SImtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMi5wMKDFJlcG9ydGVyRGF0YRJzCg1yZXBvcnRlcl90eXBlGNiPmXUgASgOMj0ua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5SZXBvcnRlckRhdGEuUmVwb3J0ZXJUeXBlQgu6SAiCAQUQASIBAFINcmVwb3J0ZXJfdHlwZRI6ChRyZXBvcnRlcl9pbnN0YW5jZV9pZBi41fpyIAEoCUID4EEDUhRyZXBvcnRlcl9pbnN0YW5jZV9pZBIlCgxjb25zb2xlX2hyZWYYlKLGRSABKAlSDGNvbnNvbGVfaHJlZhIeCghhcGlfaHJlZhix/JHNASABKAlSCGFwaV9ocmVmEjkKEWxvY2FsX3Jlc291cmNlX2lkGL242fIBIAEoCUIHukgEcgIQAVIRbG9jYWxfcmVzb3VyY2VfaWQSLgoQcmVwb3J0ZXJfdmVyc2lvbhj67siAASABKAlSEHJlcG9ydGVyX3ZlcnNpb24idAoMUmVwb3J0ZXJUeXBlEh0KGVJFUE9SVEVSX1RZUEVfVU5TUEVDSUZJRUQQABIXChNSRVBPUlRFUl9UWVBFX09USEVSEAESBwoDQUNNEAISBwoDSEJJEAMSBwoDT0NNEAQSEQoNTk9USUZJQ0FUSU9OUxAFQoYBCjJvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGExLnJlc291cmNlc1ABWk5naXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXNiBnByb3RvMw",
    [file_google_api_field_behavior, file_buf_validate_validate],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.ReporterData
 */
export type ReporterData =
  Message<"kessel.inventory.v1beta1.resources.ReporterData"> & {
    /**
     * @generated from field: kessel.inventory.v1beta1.resources.ReporterData.ReporterType reporter_type = 245778392 [json_name = "reporter_type"];
     */
    reporterType: ReporterData_ReporterType;

    /**
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     *
     * @generated from field: string reporter_instance_id = 241085112 [json_name = "reporter_instance_id"];
     */
    reporterInstanceId: string;

    /**
     * The URL for this resource in the reporter's management UI console. For
     * example this would be the cluster URL in the HCC Console for an OCM
     * reported cluster.
     *
     * @generated from field: string console_href = 145854740 [json_name = "console_href"];
     */
    consoleHref: string;

    /**
     * Reporter specific API link to the resource.
     *
     * @generated from field: string api_href = 430210609 [json_name = "api_href"];
     */
    apiHref: string;

    /**
     * The ID assigned to this resource by the reporter, for example OCM cluster
     * ID, HBI's host id, or ACM managed cluster name etc.
     *
     * @generated from field: string local_resource_id = 508976189 [json_name = "local_resource_id"];
     */
    localResourceId: string;

    /**
     * version of the reporter
     *
     * @generated from field: string reporter_version = 269629306 [json_name = "reporter_version"];
     */
    reporterVersion: string;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.ReporterData.
 * Use `create(ReporterDataSchema)` to create a new message.
 */
export const ReporterDataSchema: GenMessage<ReporterData> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_reporter_data, 0);

/**
 * @generated from enum kessel.inventory.v1beta1.resources.ReporterData.ReporterType
 */
export enum ReporterData_ReporterType {
  /**
   * @generated from enum value: REPORTER_TYPE_UNSPECIFIED = 0;
   */
  REPORTER_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: REPORTER_TYPE_OTHER = 1;
   */
  REPORTER_TYPE_OTHER = 1,

  /**
   * @generated from enum value: ACM = 2;
   */
  ACM = 2,

  /**
   * @generated from enum value: HBI = 3;
   */
  HBI = 3,

  /**
   * @generated from enum value: OCM = 4;
   */
  OCM = 4,

  /**
   * @generated from enum value: NOTIFICATIONS = 5;
   */
  NOTIFICATIONS = 5,
}

/**
 * Describes the enum kessel.inventory.v1beta1.resources.ReporterData.ReporterType.
 */
export const ReporterData_ReporterTypeSchema: GenEnum<ReporterData_ReporterType> =
  /*@__PURE__*/
  enumDesc(file_kessel_inventory_v1beta1_resources_reporter_data, 0, 0);
