// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/resource_label.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/resource_label.proto.
 */
export const file_kessel_inventory_v1beta1_resources_resource_label: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjdrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL3Jlc291cmNlX2xhYmVsLnByb3RvEiJrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzIkIKDVJlc291cmNlTGFiZWwSFgoDa2V5GN+8BiABKAlCB7pIBHICEAESGQoFdmFsdWUY8aKyNSABKAlCB7pIBHICEAFChgEKMm9yZy5wcm9qZWN0X2tlc3NlbC5hcGkuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzUAFaTmdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGExL3Jlc291cmNlc2IGcHJvdG8z",
    [file_buf_validate_validate],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.ResourceLabel
 */
export type ResourceLabel =
  Message<"kessel.inventory.v1beta1.resources.ResourceLabel"> & {
    /**
     * @generated from field: string key = 106079;
     */
    key: string;

    /**
     * @generated from field: string value = 111972721;
     */
    value: string;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.ResourceLabel.
 * Use `create(ResourceLabelSchema)` to create a new message.
 */
export const ResourceLabelSchema: GenMessage<ResourceLabel> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_resource_label, 0);
