// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/resources/rhel_hosts_service.proto (package kessel.inventory.v1beta1.resources, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../google/api/annotations_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { RhelHost } from "./rhel_host_pb";
import { file_kessel_inventory_v1beta1_resources_rhel_host } from "./rhel_host_pb";
import type { ReporterData } from "./reporter_data_pb";
import { file_kessel_inventory_v1beta1_resources_reporter_data } from "./reporter_data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/resources/rhel_hosts_service.proto.
 */
export const file_kessel_inventory_v1beta1_resources_rhel_hosts_service: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjtrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL3JoZWxfaG9zdHNfc2VydmljZS5wcm90bxIia2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcyJrChVDcmVhdGVSaGVsSG9zdFJlcXVlc3QSUgoJcmhlbF9ob3N0GAEgASgLMiwua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5SaGVsSG9zdEIGukgDyAEBUglyaGVsX2hvc3QiGAoWQ3JlYXRlUmhlbEhvc3RSZXNwb25zZSJrChVVcGRhdGVSaGVsSG9zdFJlcXVlc3QSUgoJcmhlbF9ob3N0GAEgASgLMiwua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5SaGVsSG9zdEIGukgDyAEBUglyaGVsX2hvc3QiGAoWVXBkYXRlUmhlbEhvc3RSZXNwb25zZSJ3ChVEZWxldGVSaGVsSG9zdFJlcXVlc3QSXgoNcmVwb3J0ZXJfZGF0YRgBIAEoCzIwLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuUmVwb3J0ZXJEYXRhQga6SAPIAQFSDXJlcG9ydGVyX2RhdGEiGAoWRGVsZXRlUmhlbEhvc3RSZXNwb25zZTLdBAoVS2Vzc2VsUmhlbEhvc3RTZXJ2aWNlEr8BCg5DcmVhdGVSaGVsSG9zdBI5Lmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuQ3JlYXRlUmhlbEhvc3RSZXF1ZXN0Gjoua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5DcmVhdGVSaGVsSG9zdFJlc3BvbnNlIjaC0+STAjA6ASoiKy9hcGkvaW52ZW50b3J5L3YxYmV0YTEvcmVzb3VyY2VzL3JoZWwtaG9zdHMSvwEKDlVwZGF0ZVJoZWxIb3N0Ejkua2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlc291cmNlcy5VcGRhdGVSaGVsSG9zdFJlcXVlc3QaOi5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzLlVwZGF0ZVJoZWxIb3N0UmVzcG9uc2UiNoLT5JMCMDoBKhorL2FwaS9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXMvcmhlbC1ob3N0cxK/AQoORGVsZXRlUmhlbEhvc3QSOS5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVzb3VyY2VzLkRlbGV0ZVJoZWxIb3N0UmVxdWVzdBo6Lmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZXNvdXJjZXMuRGVsZXRlUmhlbEhvc3RSZXNwb25zZSI2gtPkkwIwOgEqKisvYXBpL2ludmVudG9yeS92MWJldGExL3Jlc291cmNlcy9yaGVsLWhvc3RzQoYBCjJvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGExLnJlc291cmNlc1ABWk5naXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMS9yZXNvdXJjZXNiBnByb3RvMw",
    [
      file_google_api_annotations,
      file_buf_validate_validate,
      file_kessel_inventory_v1beta1_resources_rhel_host,
      file_kessel_inventory_v1beta1_resources_reporter_data,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.resources.CreateRhelHostRequest
 */
export type CreateRhelHostRequest =
  Message<"kessel.inventory.v1beta1.resources.CreateRhelHostRequest"> & {
    /**
     * The Rhel Host to create in Kessel Asset Inventory
     *
     * @generated from field: kessel.inventory.v1beta1.resources.RhelHost rhel_host = 1 [json_name = "rhel_host"];
     */
    rhelHost?: RhelHost;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.CreateRhelHostRequest.
 * Use `create(CreateRhelHostRequestSchema)` to create a new message.
 */
export const CreateRhelHostRequestSchema: GenMessage<CreateRhelHostRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_rhel_hosts_service, 0);

/**
 * @generated from message kessel.inventory.v1beta1.resources.CreateRhelHostResponse
 */
export type CreateRhelHostResponse =
  Message<"kessel.inventory.v1beta1.resources.CreateRhelHostResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta1.resources.CreateRhelHostResponse.
 * Use `create(CreateRhelHostResponseSchema)` to create a new message.
 */
export const CreateRhelHostResponseSchema: GenMessage<CreateRhelHostResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_rhel_hosts_service, 1);

/**
 * @generated from message kessel.inventory.v1beta1.resources.UpdateRhelHostRequest
 */
export type UpdateRhelHostRequest =
  Message<"kessel.inventory.v1beta1.resources.UpdateRhelHostRequest"> & {
    /**
     * The resource to be updated will be defined by
     * \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
     * from the request body.
     *
     * @generated from field: kessel.inventory.v1beta1.resources.RhelHost rhel_host = 1 [json_name = "rhel_host"];
     */
    rhelHost?: RhelHost;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.UpdateRhelHostRequest.
 * Use `create(UpdateRhelHostRequestSchema)` to create a new message.
 */
export const UpdateRhelHostRequestSchema: GenMessage<UpdateRhelHostRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_rhel_hosts_service, 2);

/**
 * @generated from message kessel.inventory.v1beta1.resources.UpdateRhelHostResponse
 */
export type UpdateRhelHostResponse =
  Message<"kessel.inventory.v1beta1.resources.UpdateRhelHostResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta1.resources.UpdateRhelHostResponse.
 * Use `create(UpdateRhelHostResponseSchema)` to create a new message.
 */
export const UpdateRhelHostResponseSchema: GenMessage<UpdateRhelHostResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_rhel_hosts_service, 3);

/**
 * @generated from message kessel.inventory.v1beta1.resources.DeleteRhelHostRequest
 */
export type DeleteRhelHostRequest =
  Message<"kessel.inventory.v1beta1.resources.DeleteRhelHostRequest"> & {
    /**
     * The resource to be updated will be defined by
     * \"<reporter_data.reporter_type>:<reporter_instaance_id>:<reporter_data.local_resource_id>\"
     * from the request body.
     *
     * @generated from field: kessel.inventory.v1beta1.resources.ReporterData reporter_data = 1 [json_name = "reporter_data"];
     */
    reporterData?: ReporterData;
  };

/**
 * Describes the message kessel.inventory.v1beta1.resources.DeleteRhelHostRequest.
 * Use `create(DeleteRhelHostRequestSchema)` to create a new message.
 */
export const DeleteRhelHostRequestSchema: GenMessage<DeleteRhelHostRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_rhel_hosts_service, 4);

/**
 * @generated from message kessel.inventory.v1beta1.resources.DeleteRhelHostResponse
 */
export type DeleteRhelHostResponse =
  Message<"kessel.inventory.v1beta1.resources.DeleteRhelHostResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta1.resources.DeleteRhelHostResponse.
 * Use `create(DeleteRhelHostResponseSchema)` to create a new message.
 */
export const DeleteRhelHostResponseSchema: GenMessage<DeleteRhelHostResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_resources_rhel_hosts_service, 5);

/**
 * @generated from service kessel.inventory.v1beta1.resources.KesselRhelHostService
 */
export const KesselRhelHostService: GenService<{
  /**
   * @generated from rpc kessel.inventory.v1beta1.resources.KesselRhelHostService.CreateRhelHost
   */
  createRhelHost: {
    methodKind: "unary";
    input: typeof CreateRhelHostRequestSchema;
    output: typeof CreateRhelHostResponseSchema;
  };
  /**
   * @generated from rpc kessel.inventory.v1beta1.resources.KesselRhelHostService.UpdateRhelHost
   */
  updateRhelHost: {
    methodKind: "unary";
    input: typeof UpdateRhelHostRequestSchema;
    output: typeof UpdateRhelHostResponseSchema;
  };
  /**
   * @generated from rpc kessel.inventory.v1beta1.resources.KesselRhelHostService.DeleteRhelHost
   */
  deleteRhelHost: {
    methodKind: "unary";
    input: typeof DeleteRhelHostRequestSchema;
    output: typeof DeleteRhelHostResponseSchema;
  };
}> =
  /*@__PURE__*/
  serviceDesc(file_kessel_inventory_v1beta1_resources_rhel_hosts_service, 0);
