// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_detail.proto (package kessel.inventory.v1beta1.relationships, syntax proto3)
/* eslint-disable */

import type {
  GenEnum,
  GenFile,
  GenMessage,
} from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../../google/api/field_behavior_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_detail.proto.
 */
export const file_kessel_inventory_v1beta1_relationships_k8spolicy_ispropagatedto_k8scluster_detail: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CldrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVsYXRpb25zaGlwcy9rOHNwb2xpY3lfaXNwcm9wYWdhdGVkdG9fazhzY2x1c3Rlcl9kZXRhaWwucHJvdG8SJmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZWxhdGlvbnNoaXBzItcCCidLOFNQb2xpY3lJc1Byb3BhZ2F0ZWRUb0s4U0NsdXN0ZXJEZXRhaWwSLAoNazhzX3BvbGljeV9pZBi4sc5rIAEoCUID4EEDUg1rOHNfcG9saWN5X2lkEi4KDms4c19jbHVzdGVyX2lkGIDLyXIgASgJQgPgQQNSDms4c19jbHVzdGVyX2lkEncKBnN0YXR1cxiP4MipASABKA4yVi5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVsYXRpb25zaGlwcy5LOFNQb2xpY3lJc1Byb3BhZ2F0ZWRUb0s4U0NsdXN0ZXJEZXRhaWwuU3RhdHVzQgu6SAiCAQUQASIBACJVCgZTdGF0dXMSFgoSU1RBVFVTX1VOU1BFQ0lGSUVEEAASEAoMU1RBVFVTX09USEVSEAESDgoKVklPTEFUSU9OUxACEhEKDU5PX1ZJT0xBVElPTlMQA0K8AQo2b3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMS5yZWxhdGlvbnNoaXBzQixLOFNQb2xpY3lJc1Byb3BhZ2F0ZWRUb0s4U0NsdXN0ZXJEZXRhaWxQcm90b1ABWlJnaXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMS9yZWxhdGlvbnNoaXBzYgZwcm90bzM",
    [file_google_api_field_behavior, file_buf_validate_validate],
  );

/**
 * @generated from message kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail
 */
export type K8SPolicyIsPropagatedToK8SClusterDetail =
  Message<"kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail"> & {
    /**
     * The resource ID assigned to the resource by Kessel Asset Inventory.
     *
     * @generated from field: string k8s_policy_id = 225679544 [json_name = "k8s_policy_id"];
     */
    k8sPolicyId: string;

    /**
     * The resource ID assigned to the resource by Kessel Asset Inventory.
     *
     * @generated from field: string k8s_cluster_id = 240280960 [json_name = "k8s_cluster_id"];
     */
    k8sClusterId: string;

    /**
     * @generated from field: kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status status = 355610639;
     */
    status: K8SPolicyIsPropagatedToK8SClusterDetail_Status;
  };

/**
 * Describes the message kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.
 * Use `create(K8SPolicyIsPropagatedToK8SClusterDetailSchema)` to create a new message.
 */
export const K8SPolicyIsPropagatedToK8SClusterDetailSchema: GenMessage<K8SPolicyIsPropagatedToK8SClusterDetail> =
  /*@__PURE__*/
  messageDesc(
    file_kessel_inventory_v1beta1_relationships_k8spolicy_ispropagatedto_k8scluster_detail,
    0,
  );

/**
 * the aggregate status of the cluster
 *
 * @generated from enum kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status
 */
export enum K8SPolicyIsPropagatedToK8SClusterDetail_Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  STATUS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_OTHER = 1;
   */
  STATUS_OTHER = 1,

  /**
   * @generated from enum value: VIOLATIONS = 2;
   */
  VIOLATIONS = 2,

  /**
   * @generated from enum value: NO_VIOLATIONS = 3;
   */
  NO_VIOLATIONS = 3,
}

/**
 * Describes the enum kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status.
 */
export const K8SPolicyIsPropagatedToK8SClusterDetail_StatusSchema: GenEnum<K8SPolicyIsPropagatedToK8SClusterDetail_Status> =
  /*@__PURE__*/
  enumDesc(
    file_kessel_inventory_v1beta1_relationships_k8spolicy_ispropagatedto_k8scluster_detail,
    0,
    0,
  );
