// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster.proto (package kessel.inventory.v1beta1.relationships, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_pb";
import { file_kessel_inventory_v1beta1_relationships_metadata } from "./metadata_pb";
import type { ReporterData } from "./reporter_data_pb";
import { file_kessel_inventory_v1beta1_relationships_reporter_data } from "./reporter_data_pb";
import type { K8SPolicyIsPropagatedToK8SClusterDetail } from "./k8spolicy_ispropagatedto_k8scluster_detail_pb";
import { file_kessel_inventory_v1beta1_relationships_k8spolicy_ispropagatedto_k8scluster_detail } from "./k8spolicy_ispropagatedto_k8scluster_detail_pb";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster.proto.
 */
export const file_kessel_inventory_v1beta1_relationships_k8spolicy_ispropagatedto_k8scluster: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ClBrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVsYXRpb25zaGlwcy9rOHNwb2xpY3lfaXNwcm9wYWdhdGVkdG9fazhzY2x1c3Rlci5wcm90bxIma2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlbGF0aW9uc2hpcHMi4QIKIUs4U1BvbGljeUlzUHJvcGFnYXRlZFRvSzhTQ2x1c3RlchJKCghtZXRhZGF0YRgBIAEoCzIwLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZWxhdGlvbnNoaXBzLk1ldGFkYXRhQga6SAPYAQMSZQoNcmVwb3J0ZXJfZGF0YRjJ0Pp0IAEoCzI0Lmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZWxhdGlvbnNoaXBzLlJlcG9ydGVyRGF0YUIGukgDyAEBUg1yZXBvcnRlcl9kYXRhEogBChFyZWxhdGlvbnNoaXBfZGF0YRjLx4EBIAEoCzJPLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMS5yZWxhdGlvbnNoaXBzLks4U1BvbGljeUlzUHJvcGFnYXRlZFRvSzhTQ2x1c3RlckRldGFpbEIGukgDyAEBUhFyZWxhdGlvbnNoaXBfZGF0YUK2AQo2b3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMS5yZWxhdGlvbnNoaXBzQiZLOFNQb2xpY3lJc1Byb3BhZ2F0ZWRUb0s4U0NsdXN0ZXJQcm90b1ABWlJnaXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMS9yZWxhdGlvbnNoaXBzYgZwcm90bzM",
    [
      file_kessel_inventory_v1beta1_relationships_metadata,
      file_kessel_inventory_v1beta1_relationships_reporter_data,
      file_kessel_inventory_v1beta1_relationships_k8spolicy_ispropagatedto_k8scluster_detail,
      file_buf_validate_validate,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SCluster
 */
export type K8SPolicyIsPropagatedToK8SCluster =
  Message<"kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SCluster"> & {
    /**
     * Metadata about this resource
     *
     * @generated from field: kessel.inventory.v1beta1.relationships.Metadata metadata = 1;
     */
    metadata?: Metadata;

    /**
     * Write only reporter specific data
     *
     * @generated from field: kessel.inventory.v1beta1.relationships.ReporterData reporter_data = 245278793 [json_name = "reporter_data"];
     */
    reporterData?: ReporterData;

    /**
     * @generated from field: kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail relationship_data = 2122699 [json_name = "relationship_data"];
     */
    relationshipData?: K8SPolicyIsPropagatedToK8SClusterDetail;
  };

/**
 * Describes the message kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SCluster.
 * Use `create(K8SPolicyIsPropagatedToK8SClusterSchema)` to create a new message.
 */
export const K8SPolicyIsPropagatedToK8SClusterSchema: GenMessage<K8SPolicyIsPropagatedToK8SCluster> =
  /*@__PURE__*/
  messageDesc(
    file_kessel_inventory_v1beta1_relationships_k8spolicy_ispropagatedto_k8scluster,
    0,
  );
