// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/relationships/metadata.proto (package kessel.inventory.v1beta1.relationships, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import { file_google_api_field_behavior } from "../../../../google/api/field_behavior_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/relationships/metadata.proto.
 */
export const file_kessel_inventory_v1beta1_relationships_metadata: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjVrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVsYXRpb25zaGlwcy9tZXRhZGF0YS5wcm90bxIma2Vzc2VsLmludmVudG9yeS52MWJldGExLnJlbGF0aW9uc2hpcHMiugIKCE1ldGFkYXRhEhAKAmlkGJwaIAEoCUID4EEDEjQKEXJlbGF0aW9uc2hpcF90eXBlGOTp13cgASgJQgPgQQNSEXJlbGF0aW9uc2hpcF90eXBlEkAKCmNyZWF0ZWRfYXQYyBogASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDUgpjcmVhdGVkX2F0EkAKCnVwZGF0ZWRfYXQYyRogASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDUgp1cGRhdGVkX2F0EkAKCmRlbGV0ZWRfYXQYyhogASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDUgpkZWxldGVkX2F0EiAKBm9yZ19pZBisGyABKAlCB7pIBHICEAFSBm9yZ19pZEKOAQo2b3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMS5yZWxhdGlvbnNoaXBzUAFaUmdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGExL3JlbGF0aW9uc2hpcHNiBnByb3RvMw",
    [
      file_buf_validate_validate,
      file_google_api_field_behavior,
      file_google_protobuf_timestamp,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.relationships.Metadata
 */
export type Metadata =
  Message<"kessel.inventory.v1beta1.relationships.Metadata"> & {
    /**
     * Kessel Asset Inventory generated identifier.
     *
     * @generated from field: string id = 3356;
     */
    id: string;

    /**
     * The type of Resource relationship
     *
     * @generated from field: string relationship_type = 251000036 [json_name = "relationship_type"];
     */
    relationshipType: string;

    /**
     * Date and time when the inventory item was first reported.
     *
     * @generated from field: google.protobuf.Timestamp created_at = 3400 [json_name = "created_at"];
     */
    createdAt?: Timestamp;

    /**
     * Date and time when the inventory item was last updated.
     *
     * @generated from field: google.protobuf.Timestamp updated_at = 3401 [json_name = "updated_at"];
     */
    updatedAt?: Timestamp;

    /**
     * Date and time when the inventory item was deleted.
     *
     * @generated from field: google.protobuf.Timestamp deleted_at = 3402 [json_name = "deleted_at"];
     */
    deletedAt?: Timestamp;

    /**
     * The org id in which this resource is a member for access control.  A
     * resource can only be a member of one org.
     *
     * @generated from field: string org_id = 3500 [json_name = "org_id"];
     */
    orgId: string;
  };

/**
 * Describes the message kessel.inventory.v1beta1.relationships.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_relationships_metadata, 0);
