// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta1/relationships/reporter_data.proto (package kessel.inventory.v1beta1.relationships, syntax proto3)
/* eslint-disable */

import type {
  GenEnum,
  GenFile,
  GenMessage,
} from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../../google/api/field_behavior_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta1/relationships/reporter_data.proto.
 */
export const file_kessel_inventory_v1beta1_relationships_reporter_data: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjprZXNzZWwvaW52ZW50b3J5L3YxYmV0YTEvcmVsYXRpb25zaGlwcy9yZXBvcnRlcl9kYXRhLnByb3RvEiZrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVsYXRpb25zaGlwcyKUBQoMUmVwb3J0ZXJEYXRhEncKDXJlcG9ydGVyX3R5cGUY2Y+ZdSABKA4yQS5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTEucmVsYXRpb25zaGlwcy5SZXBvcnRlckRhdGEuUmVwb3J0ZXJUeXBlQgu6SAiCAQUQASIBAFINcmVwb3J0ZXJfdHlwZRI6ChRyZXBvcnRlcl9pbnN0YW5jZV9pZBi61fpyIAEoCUID4EEDUhRyZXBvcnRlcl9pbnN0YW5jZV9pZBIuChByZXBvcnRlcl92ZXJzaW9uGPvuyIABIAEoCVIQcmVwb3J0ZXJfdmVyc2lvbhJKCg5maXJzdF9yZXBvcnRlZBiB7c4GIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCA+BBA1IOZmlyc3RfcmVwb3J0ZWQSSQoNbGFzdF9yZXBvcnRlZBiMnZDQASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgPgQQNSDWxhc3RfcmVwb3J0ZWQSSQoZc3ViamVjdF9sb2NhbF9yZXNvdXJjZV9pZBi+uNnyASABKAlCB7pIBHICEAFSGXN1YmplY3RfbG9jYWxfcmVzb3VyY2VfaWQSRwoYb2JqZWN0X2xvY2FsX3Jlc291cmNlX2lkGL+42fIBIAEoCUIHukgEcgIQAVIYb2JqZWN0X2xvY2FsX3Jlc291cmNlX2lkInQKDFJlcG9ydGVyVHlwZRIdChlSRVBPUlRFUl9UWVBFX1VOU1BFQ0lGSUVEEAASFwoTUkVQT1JURVJfVFlQRV9PVEhFUhABEgcKA0FDTRACEgcKA0hCSRADEgcKA09DTRAEEhEKDU5PVElGSUNBVElPTlMQBUKOAQo2b3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMS5yZWxhdGlvbnNoaXBzUAFaUmdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGExL3JlbGF0aW9uc2hpcHNiBnByb3RvMw",
    [
      file_google_api_field_behavior,
      file_google_protobuf_timestamp,
      file_buf_validate_validate,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta1.relationships.ReporterData
 */
export type ReporterData =
  Message<"kessel.inventory.v1beta1.relationships.ReporterData"> & {
    /**
     * @generated from field: kessel.inventory.v1beta1.relationships.ReporterData.ReporterType reporter_type = 245778393 [json_name = "reporter_type"];
     */
    reporterType: ReporterData_ReporterType;

    /**
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     *
     * @generated from field: string reporter_instance_id = 241085114 [json_name = "reporter_instance_id"];
     */
    reporterInstanceId: string;

    /**
     * version of the reporter
     *
     * @generated from field: string reporter_version = 269629307 [json_name = "reporter_version"];
     */
    reporterVersion: string;

    /**
     * Date and time when the inventory item was first reported by this reporter
     *
     * @generated from field: google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported"];
     */
    firstReported?: Timestamp;

    /**
     * Date and time when the inventory item was last updated by this reporter
     *
     * @generated from field: google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported"];
     */
    lastReported?: Timestamp;

    /**
     * The ID assigned by the reporter to resource which is the subject of the relationship. For example
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     *
     * @generated from field: string subject_local_resource_id = 508976190 [json_name = "subject_local_resource_id"];
     */
    subjectLocalResourceId: string;

    /**
     * The ID assigned by the reporter to resource which is the object of the relationship. For example
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     *
     * @generated from field: string object_local_resource_id = 508976191 [json_name = "object_local_resource_id"];
     */
    objectLocalResourceId: string;
  };

/**
 * Describes the message kessel.inventory.v1beta1.relationships.ReporterData.
 * Use `create(ReporterDataSchema)` to create a new message.
 */
export const ReporterDataSchema: GenMessage<ReporterData> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta1_relationships_reporter_data, 0);

/**
 * @generated from enum kessel.inventory.v1beta1.relationships.ReporterData.ReporterType
 */
export enum ReporterData_ReporterType {
  /**
   * @generated from enum value: REPORTER_TYPE_UNSPECIFIED = 0;
   */
  REPORTER_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: REPORTER_TYPE_OTHER = 1;
   */
  REPORTER_TYPE_OTHER = 1,

  /**
   * @generated from enum value: ACM = 2;
   */
  ACM = 2,

  /**
   * @generated from enum value: HBI = 3;
   */
  HBI = 3,

  /**
   * @generated from enum value: OCM = 4;
   */
  OCM = 4,

  /**
   * @generated from enum value: NOTIFICATIONS = 5;
   */
  NOTIFICATIONS = 5,
}

/**
 * Describes the enum kessel.inventory.v1beta1.relationships.ReporterData.ReporterType.
 */
export const ReporterData_ReporterTypeSchema: GenEnum<ReporterData_ReporterType> =
  /*@__PURE__*/
  enumDesc(file_kessel_inventory_v1beta1_relationships_reporter_data, 0, 0);
