// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1/health.proto (package kessel.inventory.v1, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1/health.proto.
 */
export const file_kessel_inventory_v1_health: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CiBrZXNzZWwvaW52ZW50b3J5L3YxL2hlYWx0aC5wcm90bxITa2Vzc2VsLmludmVudG9yeS52MSIRCg9HZXRMaXZlelJlcXVlc3QiMAoQR2V0TGl2ZXpSZXNwb25zZRIOCgZzdGF0dXMYASABKAkSDAoEY29kZRgCIAEoDSISChBHZXRSZWFkeXpSZXF1ZXN0IjEKEUdldFJlYWR5elJlc3BvbnNlEg4KBnN0YXR1cxgBIAEoCRIMCgRjb2RlGAIgASgNMpYCChxLZXNzZWxJbnZlbnRvcnlIZWFsdGhTZXJ2aWNlEngKCEdldExpdmV6EiQua2Vzc2VsLmludmVudG9yeS52MS5HZXRMaXZlelJlcXVlc3QaJS5rZXNzZWwuaW52ZW50b3J5LnYxLkdldExpdmV6UmVzcG9uc2UiH4LT5JMCGRIXL2FwaS9pbnZlbnRvcnkvdjEvbGl2ZXoSfAoJR2V0UmVhZHl6EiUua2Vzc2VsLmludmVudG9yeS52MS5HZXRSZWFkeXpSZXF1ZXN0GiYua2Vzc2VsLmludmVudG9yeS52MS5HZXRSZWFkeXpSZXNwb25zZSIggtPkkwIaEhgvYXBpL2ludmVudG9yeS92MS9yZWFkeXpCaAojb3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFQAVo/Z2l0aHViLmNvbS9wcm9qZWN0LWtlc3NlbC9pbnZlbnRvcnktYXBpL2FwaS9rZXNzZWwvaW52ZW50b3J5L3YxYgZwcm90bzM",
    [file_google_api_annotations],
  );

/**
 * @generated from message kessel.inventory.v1.GetLivezRequest
 */
export type GetLivezRequest =
  Message<"kessel.inventory.v1.GetLivezRequest"> & {};

/**
 * Describes the message kessel.inventory.v1.GetLivezRequest.
 * Use `create(GetLivezRequestSchema)` to create a new message.
 */
export const GetLivezRequestSchema: GenMessage<GetLivezRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1_health, 0);

/**
 * @generated from message kessel.inventory.v1.GetLivezResponse
 */
export type GetLivezResponse =
  Message<"kessel.inventory.v1.GetLivezResponse"> & {
    /**
     * @generated from field: string status = 1;
     */
    status: string;

    /**
     * @generated from field: uint32 code = 2;
     */
    code: number;
  };

/**
 * Describes the message kessel.inventory.v1.GetLivezResponse.
 * Use `create(GetLivezResponseSchema)` to create a new message.
 */
export const GetLivezResponseSchema: GenMessage<GetLivezResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1_health, 1);

/**
 * @generated from message kessel.inventory.v1.GetReadyzRequest
 */
export type GetReadyzRequest =
  Message<"kessel.inventory.v1.GetReadyzRequest"> & {};

/**
 * Describes the message kessel.inventory.v1.GetReadyzRequest.
 * Use `create(GetReadyzRequestSchema)` to create a new message.
 */
export const GetReadyzRequestSchema: GenMessage<GetReadyzRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1_health, 2);

/**
 * @generated from message kessel.inventory.v1.GetReadyzResponse
 */
export type GetReadyzResponse =
  Message<"kessel.inventory.v1.GetReadyzResponse"> & {
    /**
     * @generated from field: string status = 1;
     */
    status: string;

    /**
     * @generated from field: uint32 code = 2;
     */
    code: number;
  };

/**
 * Describes the message kessel.inventory.v1.GetReadyzResponse.
 * Use `create(GetReadyzResponseSchema)` to create a new message.
 */
export const GetReadyzResponseSchema: GenMessage<GetReadyzResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1_health, 3);

/**
 * @generated from service kessel.inventory.v1.KesselInventoryHealthService
 */
export const KesselInventoryHealthService: GenService<{
  /**
   * @generated from rpc kessel.inventory.v1.KesselInventoryHealthService.GetLivez
   */
  getLivez: {
    methodKind: "unary";
    input: typeof GetLivezRequestSchema;
    output: typeof GetLivezResponseSchema;
  };
  /**
   * @generated from rpc kessel.inventory.v1.KesselInventoryHealthService.GetReadyz
   */
  getReadyz: {
    methodKind: "unary";
    input: typeof GetReadyzRequestSchema;
    output: typeof GetReadyzResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_kessel_inventory_v1_health, 0);
