// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/acquire_lock_response.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: AcquireLockResponse is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 */
export interface AcquireLockResponse {
  lockToken?: string | undefined;
}

function createBaseAcquireLockResponse(): AcquireLockResponse {
  return { lockToken: "" };
}

export const AcquireLockResponse = {
  encode(
    message: AcquireLockResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.lockToken !== undefined && message.lockToken !== "") {
      writer.uint32(10).string(message.lockToken);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AcquireLockResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAcquireLockResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.lockToken = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AcquireLockResponse {
    return {
      lockToken: isSet(object.lockToken)
        ? globalThis.String(object.lockToken)
        : "",
    };
  },

  toJSON(message: AcquireLockResponse): unknown {
    const obj: any = {};
    if (message.lockToken !== undefined && message.lockToken !== "") {
      obj.lockToken = message.lockToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AcquireLockResponse>, I>>(
    base?: I,
  ): AcquireLockResponse {
    return AcquireLockResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AcquireLockResponse>, I>>(
    object: I,
  ): AcquireLockResponse {
    const message = createBaseAcquireLockResponse();
    message.lockToken = object.lockToken ?? "";
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
