// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/allowed.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file kessel/inventory/v1beta2/allowed.proto.
 */
export const file_kessel_inventory_v1beta2_allowed: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CiZrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvYWxsb3dlZC5wcm90bxIYa2Vzc2VsLmludmVudG9yeS52MWJldGEyKkcKB0FsbG93ZWQSFwoTQUxMT1dFRF9VTlNQRUNJRklFRBAAEhAKDEFMTE9XRURfVFJVRRABEhEKDUFMTE9XRURfRkFMU0UQAkJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
  );

/**
 * @generated from enum kessel.inventory.v1beta2.Allowed
 */
export enum Allowed {
  /**
   * @generated from enum value: ALLOWED_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ALLOWED_TRUE = 1;
   */
  TRUE = 1,

  /**
   * ALLOWED_CONDITIONAL = 3; // uncomment when used
   *
   * @generated from enum value: ALLOWED_FALSE = 2;
   */
  FALSE = 2,
}

/**
 * Describes the enum kessel.inventory.v1beta2.Allowed.
 */
export const AllowedSchema: GenEnum<Allowed> =
  /*@__PURE__*/
  enumDesc(file_kessel_inventory_v1beta2_allowed, 0);
