// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/check_for_update_bulk_request.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { CheckBulkRequestItem } from "./check_bulk_request";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * CheckForUpdateBulkRequest allows checking multiple "can subject update resource?" permissions
 * in a single request. Each check is strongly consistent (same semantics as CheckForUpdate).
 * This is more efficient than making individual CheckForUpdate calls when verifying update
 * permissions for multiple resource-subject-relation combinations.
 */
export interface CheckForUpdateBulkRequest {
  items?: CheckBulkRequestItem[] | undefined;
}

function createBaseCheckForUpdateBulkRequest(): CheckForUpdateBulkRequest {
  return { items: [] };
}

export const CheckForUpdateBulkRequest = {
  encode(
    message: CheckForUpdateBulkRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.items !== undefined && message.items.length !== 0) {
      for (const v of message.items) {
        CheckBulkRequestItem.encode(v!, writer.uint32(10).fork()).ldelim();
      }
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CheckForUpdateBulkRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckForUpdateBulkRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.items!.push(
            CheckBulkRequestItem.decode(reader, reader.uint32()),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckForUpdateBulkRequest {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => CheckBulkRequestItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CheckForUpdateBulkRequest): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => CheckBulkRequestItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckForUpdateBulkRequest>, I>>(
    base?: I,
  ): CheckForUpdateBulkRequest {
    return CheckForUpdateBulkRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckForUpdateBulkRequest>, I>>(
    object: I,
  ): CheckForUpdateBulkRequest {
    const message = createBaseCheckForUpdateBulkRequest();
    message.items =
      object.items?.map((e) => CheckBulkRequestItem.fromPartial(e)) || [];
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };
