// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/check_for_update_response.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Allowed } from "./allowed_pb";
import { file_kessel_inventory_v1beta2_allowed } from "./allowed_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/check_for_update_response.proto.
 */
export const file_kessel_inventory_v1beta2_check_for_update_response: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjhrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvY2hlY2tfZm9yX3VwZGF0ZV9yZXNwb25zZS5wcm90bxIYa2Vzc2VsLmludmVudG9yeS52MWJldGEyIkwKFkNoZWNrRm9yVXBkYXRlUmVzcG9uc2USMgoHYWxsb3dlZBgBIAEoDjIhLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMi5BbGxvd2VkQnIKKG9yZy5wcm9qZWN0X2tlc3NlbC5hcGkuaW52ZW50b3J5LnYxYmV0YTJQAVpEZ2l0aHViLmNvbS9wcm9qZWN0LWtlc3NlbC9pbnZlbnRvcnktYXBpL2FwaS9rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTJiBnByb3RvMw",
    [file_kessel_inventory_v1beta2_allowed],
  );

/**
 * @generated from message kessel.inventory.v1beta2.CheckForUpdateResponse
 */
export type CheckForUpdateResponse =
  Message<"kessel.inventory.v1beta2.CheckForUpdateResponse"> & {
    /**
     * @generated from field: kessel.inventory.v1beta2.Allowed allowed = 1;
     */
    allowed: Allowed;
  };

/**
 * Describes the message kessel.inventory.v1beta2.CheckForUpdateResponse.
 * Use `create(CheckForUpdateResponseSchema)` to create a new message.
 */
export const CheckForUpdateResponseSchema: GenMessage<CheckForUpdateResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_check_for_update_response, 0);
