// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/check_for_update_request.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { ResourceReference } from "./resource_reference_pb";
import { file_kessel_inventory_v1beta2_resource_reference } from "./resource_reference_pb";
import type { SubjectReference } from "./subject_reference_pb";
import { file_kessel_inventory_v1beta2_subject_reference } from "./subject_reference_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/check_for_update_request.proto.
 */
export const file_kessel_inventory_v1beta2_check_for_update_request: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjdrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvY2hlY2tfZm9yX3VwZGF0ZV9yZXF1ZXN0LnByb3RvEhhrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIivAEKFUNoZWNrRm9yVXBkYXRlUmVxdWVzdBJDCgZvYmplY3QYASABKAsyKy5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIuUmVzb3VyY2VSZWZlcmVuY2VCBrpIA8gBARIZCghyZWxhdGlvbhgCIAEoCUIHukgEcgIQARJDCgdzdWJqZWN0GAMgASgLMioua2Vzc2VsLmludmVudG9yeS52MWJldGEyLlN1YmplY3RSZWZlcmVuY2VCBrpIA8gBAUJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta2_resource_reference,
      file_kessel_inventory_v1beta2_subject_reference,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta2.CheckForUpdateRequest
 */
export type CheckForUpdateRequest =
  Message<"kessel.inventory.v1beta2.CheckForUpdateRequest"> & {
    /**
     * Required parameters
     * - resource type and id
     * - permission (cannot be derived from type as types may have multiple edit permissions Ex: https://github.com/RedHatInsights/rbac-config/blob/master/configs/prod/schemas/src/notifications.ksl#L37)
     * - user (possibly derived from an identity token)
     *
     * @generated from field: kessel.inventory.v1beta2.ResourceReference object = 1;
     */
    object?: ResourceReference;

    /**
     * @generated from field: string relation = 2;
     */
    relation: string;

    /**
     * @generated from field: kessel.inventory.v1beta2.SubjectReference subject = 3;
     */
    subject?: SubjectReference;
  };

/**
 * Describes the message kessel.inventory.v1beta2.CheckForUpdateRequest.
 * Use `create(CheckForUpdateRequestSchema)` to create a new message.
 */
export const CheckForUpdateRequestSchema: GenMessage<CheckForUpdateRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_check_for_update_request, 0);
