// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/check_self_bulk_request.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Consistency } from "./consistency";
import { ResourceReference } from "./resource_reference";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * CheckSelfBulkRequestItem represents a single permission check for the caller
 * (self) in a bulk request. The subject is derived from the caller's
 * authenticated identity rather than being provided explicitly.
 */
export interface CheckSelfBulkRequestItem {
  object?: ResourceReference | undefined;
  relation?: string | undefined;
}

/**
 * CheckSelfBulkRequest allows checking multiple permissions for the caller
 * (self) in a single request. This is more efficient than making individual
 * CheckSelf calls when verifying permissions for multiple
 * resource-relation combinations.
 */
export interface CheckSelfBulkRequest {
  items?: CheckSelfBulkRequestItem[] | undefined;
  consistency?: Consistency | undefined;
}

function createBaseCheckSelfBulkRequestItem(): CheckSelfBulkRequestItem {
  return { object: undefined, relation: "" };
}

export const CheckSelfBulkRequestItem = {
  encode(
    message: CheckSelfBulkRequestItem,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.object !== undefined) {
      ResourceReference.encode(
        message.object,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.relation !== undefined && message.relation !== "") {
      writer.uint32(18).string(message.relation);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CheckSelfBulkRequestItem {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckSelfBulkRequestItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.object = ResourceReference.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.relation = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckSelfBulkRequestItem {
    return {
      object: isSet(object.object)
        ? ResourceReference.fromJSON(object.object)
        : undefined,
      relation: isSet(object.relation)
        ? globalThis.String(object.relation)
        : "",
    };
  },

  toJSON(message: CheckSelfBulkRequestItem): unknown {
    const obj: any = {};
    if (message.object !== undefined) {
      obj.object = ResourceReference.toJSON(message.object);
    }
    if (message.relation !== undefined && message.relation !== "") {
      obj.relation = message.relation;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckSelfBulkRequestItem>, I>>(
    base?: I,
  ): CheckSelfBulkRequestItem {
    return CheckSelfBulkRequestItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckSelfBulkRequestItem>, I>>(
    object: I,
  ): CheckSelfBulkRequestItem {
    const message = createBaseCheckSelfBulkRequestItem();
    message.object =
      object.object !== undefined && object.object !== null
        ? ResourceReference.fromPartial(object.object)
        : undefined;
    message.relation = object.relation ?? "";
    return message;
  },
};

function createBaseCheckSelfBulkRequest(): CheckSelfBulkRequest {
  return { items: [], consistency: undefined };
}

export const CheckSelfBulkRequest = {
  encode(
    message: CheckSelfBulkRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.items !== undefined && message.items.length !== 0) {
      for (const v of message.items) {
        CheckSelfBulkRequestItem.encode(v!, writer.uint32(10).fork()).ldelim();
      }
    }
    if (message.consistency !== undefined) {
      Consistency.encode(
        message.consistency,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CheckSelfBulkRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckSelfBulkRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.items!.push(
            CheckSelfBulkRequestItem.decode(reader, reader.uint32()),
          );
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.consistency = Consistency.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckSelfBulkRequest {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => CheckSelfBulkRequestItem.fromJSON(e))
        : [],
      consistency: isSet(object.consistency)
        ? Consistency.fromJSON(object.consistency)
        : undefined,
    };
  },

  toJSON(message: CheckSelfBulkRequest): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => CheckSelfBulkRequestItem.toJSON(e));
    }
    if (message.consistency !== undefined) {
      obj.consistency = Consistency.toJSON(message.consistency);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckSelfBulkRequest>, I>>(
    base?: I,
  ): CheckSelfBulkRequest {
    return CheckSelfBulkRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckSelfBulkRequest>, I>>(
    object: I,
  ): CheckSelfBulkRequest {
    const message = createBaseCheckSelfBulkRequest();
    message.items =
      object.items?.map((e) => CheckSelfBulkRequestItem.fromPartial(e)) || [];
    message.consistency =
      object.consistency !== undefined && object.consistency !== null
        ? Consistency.fromPartial(object.consistency)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
