// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/check_self_request.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Consistency } from "./consistency";
import { ResourceReference } from "./resource_reference";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * CheckSelfRequest performs an access check for the caller (self) against a
 * specific object and relation. The subject is derived from the caller's
 * authenticated identity rather than being provided explicitly.
 */
export interface CheckSelfRequest {
  /**
   * Required parameters (from an authz perspective)
   * - resource type and id
   * - permission (cannot be derived from the type as a type may have multiple 'read' permissions. Ex: https://github.com/RedHatInsights/rbac-config/blob/master/configs/prod/schemas/src/notifications.ksl#L31)
   *
   * The subject is implicitly the caller, as determined by the authentication
   * context, instead of being provided as a SubjectReference.
   */
  object?: ResourceReference | undefined;
  relation?: string | undefined;
  consistency?: Consistency | undefined;
}

function createBaseCheckSelfRequest(): CheckSelfRequest {
  return { object: undefined, relation: "", consistency: undefined };
}

export const CheckSelfRequest = {
  encode(
    message: CheckSelfRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.object !== undefined) {
      ResourceReference.encode(
        message.object,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.relation !== undefined && message.relation !== "") {
      writer.uint32(18).string(message.relation);
    }
    if (message.consistency !== undefined) {
      Consistency.encode(
        message.consistency,
        writer.uint32(26).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CheckSelfRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckSelfRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.object = ResourceReference.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.relation = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.consistency = Consistency.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckSelfRequest {
    return {
      object: isSet(object.object)
        ? ResourceReference.fromJSON(object.object)
        : undefined,
      relation: isSet(object.relation)
        ? globalThis.String(object.relation)
        : "",
      consistency: isSet(object.consistency)
        ? Consistency.fromJSON(object.consistency)
        : undefined,
    };
  },

  toJSON(message: CheckSelfRequest): unknown {
    const obj: any = {};
    if (message.object !== undefined) {
      obj.object = ResourceReference.toJSON(message.object);
    }
    if (message.relation !== undefined && message.relation !== "") {
      obj.relation = message.relation;
    }
    if (message.consistency !== undefined) {
      obj.consistency = Consistency.toJSON(message.consistency);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckSelfRequest>, I>>(
    base?: I,
  ): CheckSelfRequest {
    return CheckSelfRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckSelfRequest>, I>>(
    object: I,
  ): CheckSelfRequest {
    const message = createBaseCheckSelfRequest();
    message.object =
      object.object !== undefined && object.object !== null
        ? ResourceReference.fromPartial(object.object)
        : undefined;
    message.relation = object.relation ?? "";
    message.consistency =
      object.consistency !== undefined && object.consistency !== null
        ? Consistency.fromPartial(object.consistency)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
