// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/check_bulk_request.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Consistency } from "./consistency";
import { ResourceReference } from "./resource_reference";
import { SubjectReference } from "./subject_reference";

export const protobufPackage = "kessel.inventory.v1beta2";

/** CheckBulkRequestItem represents a single permission check in a bulk request. */
export interface CheckBulkRequestItem {
  object?: ResourceReference | undefined;
  relation?: string | undefined;
  subject?: SubjectReference | undefined;
}

/**
 * CheckBulkRequest allows checking multiple permissions in a single request.
 * This is more efficient than making individual Check calls when verifying permissions
 * for multiple resource-subject-relation combinations.
 */
export interface CheckBulkRequest {
  items?: CheckBulkRequestItem[] | undefined;
  consistency?: Consistency | undefined;
}

function createBaseCheckBulkRequestItem(): CheckBulkRequestItem {
  return { object: undefined, relation: "", subject: undefined };
}

export const CheckBulkRequestItem = {
  encode(
    message: CheckBulkRequestItem,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.object !== undefined) {
      ResourceReference.encode(
        message.object,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.relation !== undefined && message.relation !== "") {
      writer.uint32(18).string(message.relation);
    }
    if (message.subject !== undefined) {
      SubjectReference.encode(
        message.subject,
        writer.uint32(26).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CheckBulkRequestItem {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckBulkRequestItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.object = ResourceReference.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.relation = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.subject = SubjectReference.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckBulkRequestItem {
    return {
      object: isSet(object.object)
        ? ResourceReference.fromJSON(object.object)
        : undefined,
      relation: isSet(object.relation)
        ? globalThis.String(object.relation)
        : "",
      subject: isSet(object.subject)
        ? SubjectReference.fromJSON(object.subject)
        : undefined,
    };
  },

  toJSON(message: CheckBulkRequestItem): unknown {
    const obj: any = {};
    if (message.object !== undefined) {
      obj.object = ResourceReference.toJSON(message.object);
    }
    if (message.relation !== undefined && message.relation !== "") {
      obj.relation = message.relation;
    }
    if (message.subject !== undefined) {
      obj.subject = SubjectReference.toJSON(message.subject);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckBulkRequestItem>, I>>(
    base?: I,
  ): CheckBulkRequestItem {
    return CheckBulkRequestItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckBulkRequestItem>, I>>(
    object: I,
  ): CheckBulkRequestItem {
    const message = createBaseCheckBulkRequestItem();
    message.object =
      object.object !== undefined && object.object !== null
        ? ResourceReference.fromPartial(object.object)
        : undefined;
    message.relation = object.relation ?? "";
    message.subject =
      object.subject !== undefined && object.subject !== null
        ? SubjectReference.fromPartial(object.subject)
        : undefined;
    return message;
  },
};

function createBaseCheckBulkRequest(): CheckBulkRequest {
  return { items: [], consistency: undefined };
}

export const CheckBulkRequest = {
  encode(
    message: CheckBulkRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.items !== undefined && message.items.length !== 0) {
      for (const v of message.items) {
        CheckBulkRequestItem.encode(v!, writer.uint32(10).fork()).ldelim();
      }
    }
    if (message.consistency !== undefined) {
      Consistency.encode(
        message.consistency,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CheckBulkRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckBulkRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.items!.push(
            CheckBulkRequestItem.decode(reader, reader.uint32()),
          );
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.consistency = Consistency.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckBulkRequest {
    return {
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => CheckBulkRequestItem.fromJSON(e))
        : [],
      consistency: isSet(object.consistency)
        ? Consistency.fromJSON(object.consistency)
        : undefined,
    };
  },

  toJSON(message: CheckBulkRequest): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => CheckBulkRequestItem.toJSON(e));
    }
    if (message.consistency !== undefined) {
      obj.consistency = Consistency.toJSON(message.consistency);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckBulkRequest>, I>>(
    base?: I,
  ): CheckBulkRequest {
    return CheckBulkRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckBulkRequest>, I>>(
    object: I,
  ): CheckBulkRequest {
    const message = createBaseCheckBulkRequest();
    message.items =
      object.items?.map((e) => CheckBulkRequestItem.fromPartial(e)) || [];
    message.consistency =
      object.consistency !== undefined && object.consistency !== null
        ? Consistency.fromPartial(object.consistency)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
