// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/check_self_bulk_response.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Status } from "../../../google/rpc/status";
import { Allowed, allowedFromJSON, allowedToJSON } from "./allowed";
import { CheckSelfBulkRequestItem } from "./check_self_bulk_request";
import { ConsistencyToken } from "./consistency_token";

export const protobufPackage = "kessel.inventory.v1beta2";

/** CheckSelfBulkResponseItem represents the result of a single self-access permission check. */
export interface CheckSelfBulkResponseItem {
  allowed?: Allowed | undefined;
}

/** CheckSelfBulkResponsePair associates a self-access request item with its corresponding result. */
export interface CheckSelfBulkResponsePair {
  request?: CheckSelfBulkRequestItem | undefined;
  item?: CheckSelfBulkResponseItem | undefined;
  error?: Status | undefined;
}

/** CheckSelfBulkResponse contains the results of all self-access permission checks in the request. */
export interface CheckSelfBulkResponse {
  pairs?: CheckSelfBulkResponsePair[] | undefined;
  consistencyToken?: ConsistencyToken | undefined;
}

function createBaseCheckSelfBulkResponseItem(): CheckSelfBulkResponseItem {
  return { allowed: 0 };
}

export const CheckSelfBulkResponseItem = {
  encode(
    message: CheckSelfBulkResponseItem,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.allowed !== undefined && message.allowed !== 0) {
      writer.uint32(8).int32(message.allowed);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CheckSelfBulkResponseItem {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckSelfBulkResponseItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.allowed = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckSelfBulkResponseItem {
    return {
      allowed: isSet(object.allowed) ? allowedFromJSON(object.allowed) : 0,
    };
  },

  toJSON(message: CheckSelfBulkResponseItem): unknown {
    const obj: any = {};
    if (message.allowed !== undefined && message.allowed !== 0) {
      obj.allowed = allowedToJSON(message.allowed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckSelfBulkResponseItem>, I>>(
    base?: I,
  ): CheckSelfBulkResponseItem {
    return CheckSelfBulkResponseItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckSelfBulkResponseItem>, I>>(
    object: I,
  ): CheckSelfBulkResponseItem {
    const message = createBaseCheckSelfBulkResponseItem();
    message.allowed = object.allowed ?? 0;
    return message;
  },
};

function createBaseCheckSelfBulkResponsePair(): CheckSelfBulkResponsePair {
  return { request: undefined, item: undefined, error: undefined };
}

export const CheckSelfBulkResponsePair = {
  encode(
    message: CheckSelfBulkResponsePair,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.request !== undefined) {
      CheckSelfBulkRequestItem.encode(
        message.request,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.item !== undefined) {
      CheckSelfBulkResponseItem.encode(
        message.item,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    if (message.error !== undefined) {
      Status.encode(message.error, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CheckSelfBulkResponsePair {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckSelfBulkResponsePair();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.request = CheckSelfBulkRequestItem.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.item = CheckSelfBulkResponseItem.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.error = Status.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckSelfBulkResponsePair {
    return {
      request: isSet(object.request)
        ? CheckSelfBulkRequestItem.fromJSON(object.request)
        : undefined,
      item: isSet(object.item)
        ? CheckSelfBulkResponseItem.fromJSON(object.item)
        : undefined,
      error: isSet(object.error) ? Status.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: CheckSelfBulkResponsePair): unknown {
    const obj: any = {};
    if (message.request !== undefined) {
      obj.request = CheckSelfBulkRequestItem.toJSON(message.request);
    }
    if (message.item !== undefined) {
      obj.item = CheckSelfBulkResponseItem.toJSON(message.item);
    }
    if (message.error !== undefined) {
      obj.error = Status.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckSelfBulkResponsePair>, I>>(
    base?: I,
  ): CheckSelfBulkResponsePair {
    return CheckSelfBulkResponsePair.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckSelfBulkResponsePair>, I>>(
    object: I,
  ): CheckSelfBulkResponsePair {
    const message = createBaseCheckSelfBulkResponsePair();
    message.request =
      object.request !== undefined && object.request !== null
        ? CheckSelfBulkRequestItem.fromPartial(object.request)
        : undefined;
    message.item =
      object.item !== undefined && object.item !== null
        ? CheckSelfBulkResponseItem.fromPartial(object.item)
        : undefined;
    message.error =
      object.error !== undefined && object.error !== null
        ? Status.fromPartial(object.error)
        : undefined;
    return message;
  },
};

function createBaseCheckSelfBulkResponse(): CheckSelfBulkResponse {
  return { pairs: [], consistencyToken: undefined };
}

export const CheckSelfBulkResponse = {
  encode(
    message: CheckSelfBulkResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.pairs !== undefined && message.pairs.length !== 0) {
      for (const v of message.pairs) {
        CheckSelfBulkResponsePair.encode(v!, writer.uint32(10).fork()).ldelim();
      }
    }
    if (message.consistencyToken !== undefined) {
      ConsistencyToken.encode(
        message.consistencyToken,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CheckSelfBulkResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckSelfBulkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pairs!.push(
            CheckSelfBulkResponsePair.decode(reader, reader.uint32()),
          );
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.consistencyToken = ConsistencyToken.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckSelfBulkResponse {
    return {
      pairs: globalThis.Array.isArray(object?.pairs)
        ? object.pairs.map((e: any) => CheckSelfBulkResponsePair.fromJSON(e))
        : [],
      consistencyToken: isSet(object.consistencyToken)
        ? ConsistencyToken.fromJSON(object.consistencyToken)
        : undefined,
    };
  },

  toJSON(message: CheckSelfBulkResponse): unknown {
    const obj: any = {};
    if (message.pairs?.length) {
      obj.pairs = message.pairs.map((e) => CheckSelfBulkResponsePair.toJSON(e));
    }
    if (message.consistencyToken !== undefined) {
      obj.consistencyToken = ConsistencyToken.toJSON(message.consistencyToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckSelfBulkResponse>, I>>(
    base?: I,
  ): CheckSelfBulkResponse {
    return CheckSelfBulkResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckSelfBulkResponse>, I>>(
    object: I,
  ): CheckSelfBulkResponse {
    const message = createBaseCheckSelfBulkResponse();
    message.pairs =
      object.pairs?.map((e) => CheckSelfBulkResponsePair.fromPartial(e)) || [];
    message.consistencyToken =
      object.consistencyToken !== undefined && object.consistencyToken !== null
        ? ConsistencyToken.fromPartial(object.consistencyToken)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
