// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/check_response.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Allowed } from "./allowed_pb";
import { file_kessel_inventory_v1beta2_allowed } from "./allowed_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/check_response.proto.
 */
export const file_kessel_inventory_v1beta2_check_response: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Ci1rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvY2hlY2tfcmVzcG9uc2UucHJvdG8SGGtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMiJDCg1DaGVja1Jlc3BvbnNlEjIKB2FsbG93ZWQYASABKA4yIS5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIuQWxsb3dlZEJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
    [file_kessel_inventory_v1beta2_allowed],
  );

/**
 * @generated from message kessel.inventory.v1beta2.CheckResponse
 */
export type CheckResponse =
  Message<"kessel.inventory.v1beta2.CheckResponse"> & {
    /**
     * @generated from field: kessel.inventory.v1beta2.Allowed allowed = 1;
     */
    allowed: Allowed;
  };

/**
 * Describes the message kessel.inventory.v1beta2.CheckResponse.
 * Use `create(CheckResponseSchema)` to create a new message.
 */
export const CheckResponseSchema: GenMessage<CheckResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_check_response, 0);
