// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/check_bulk_response.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Status } from "../../../google/rpc/status";
import { Allowed, allowedFromJSON, allowedToJSON } from "./allowed";
import { CheckBulkRequestItem } from "./check_bulk_request";
import { ConsistencyToken } from "./consistency_token";

export const protobufPackage = "kessel.inventory.v1beta2";

/** CheckBulkResponseItem represents the result of a single permission check. */
export interface CheckBulkResponseItem {
  allowed?: Allowed | undefined;
}

/** CheckBulkResponsePair associates a request item with its corresponding result. */
export interface CheckBulkResponsePair {
  request?: CheckBulkRequestItem | undefined;
  item?: CheckBulkResponseItem | undefined;
  error?: Status | undefined;
}

/** CheckBulkResponse contains the results of all permission checks in the request. */
export interface CheckBulkResponse {
  pairs?: CheckBulkResponsePair[] | undefined;
  consistencyToken?: ConsistencyToken | undefined;
}

function createBaseCheckBulkResponseItem(): CheckBulkResponseItem {
  return { allowed: 0 };
}

export const CheckBulkResponseItem = {
  encode(
    message: CheckBulkResponseItem,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.allowed !== undefined && message.allowed !== 0) {
      writer.uint32(8).int32(message.allowed);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CheckBulkResponseItem {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckBulkResponseItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.allowed = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckBulkResponseItem {
    return {
      allowed: isSet(object.allowed) ? allowedFromJSON(object.allowed) : 0,
    };
  },

  toJSON(message: CheckBulkResponseItem): unknown {
    const obj: any = {};
    if (message.allowed !== undefined && message.allowed !== 0) {
      obj.allowed = allowedToJSON(message.allowed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckBulkResponseItem>, I>>(
    base?: I,
  ): CheckBulkResponseItem {
    return CheckBulkResponseItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckBulkResponseItem>, I>>(
    object: I,
  ): CheckBulkResponseItem {
    const message = createBaseCheckBulkResponseItem();
    message.allowed = object.allowed ?? 0;
    return message;
  },
};

function createBaseCheckBulkResponsePair(): CheckBulkResponsePair {
  return { request: undefined, item: undefined, error: undefined };
}

export const CheckBulkResponsePair = {
  encode(
    message: CheckBulkResponsePair,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.request !== undefined) {
      CheckBulkRequestItem.encode(
        message.request,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.item !== undefined) {
      CheckBulkResponseItem.encode(
        message.item,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    if (message.error !== undefined) {
      Status.encode(message.error, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): CheckBulkResponsePair {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckBulkResponsePair();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.request = CheckBulkRequestItem.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.item = CheckBulkResponseItem.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.error = Status.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckBulkResponsePair {
    return {
      request: isSet(object.request)
        ? CheckBulkRequestItem.fromJSON(object.request)
        : undefined,
      item: isSet(object.item)
        ? CheckBulkResponseItem.fromJSON(object.item)
        : undefined,
      error: isSet(object.error) ? Status.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: CheckBulkResponsePair): unknown {
    const obj: any = {};
    if (message.request !== undefined) {
      obj.request = CheckBulkRequestItem.toJSON(message.request);
    }
    if (message.item !== undefined) {
      obj.item = CheckBulkResponseItem.toJSON(message.item);
    }
    if (message.error !== undefined) {
      obj.error = Status.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckBulkResponsePair>, I>>(
    base?: I,
  ): CheckBulkResponsePair {
    return CheckBulkResponsePair.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckBulkResponsePair>, I>>(
    object: I,
  ): CheckBulkResponsePair {
    const message = createBaseCheckBulkResponsePair();
    message.request =
      object.request !== undefined && object.request !== null
        ? CheckBulkRequestItem.fromPartial(object.request)
        : undefined;
    message.item =
      object.item !== undefined && object.item !== null
        ? CheckBulkResponseItem.fromPartial(object.item)
        : undefined;
    message.error =
      object.error !== undefined && object.error !== null
        ? Status.fromPartial(object.error)
        : undefined;
    return message;
  },
};

function createBaseCheckBulkResponse(): CheckBulkResponse {
  return { pairs: [], consistencyToken: undefined };
}

export const CheckBulkResponse = {
  encode(
    message: CheckBulkResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.pairs !== undefined && message.pairs.length !== 0) {
      for (const v of message.pairs) {
        CheckBulkResponsePair.encode(v!, writer.uint32(10).fork()).ldelim();
      }
    }
    if (message.consistencyToken !== undefined) {
      ConsistencyToken.encode(
        message.consistencyToken,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CheckBulkResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckBulkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pairs!.push(
            CheckBulkResponsePair.decode(reader, reader.uint32()),
          );
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.consistencyToken = ConsistencyToken.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckBulkResponse {
    return {
      pairs: globalThis.Array.isArray(object?.pairs)
        ? object.pairs.map((e: any) => CheckBulkResponsePair.fromJSON(e))
        : [],
      consistencyToken: isSet(object.consistencyToken)
        ? ConsistencyToken.fromJSON(object.consistencyToken)
        : undefined,
    };
  },

  toJSON(message: CheckBulkResponse): unknown {
    const obj: any = {};
    if (message.pairs?.length) {
      obj.pairs = message.pairs.map((e) => CheckBulkResponsePair.toJSON(e));
    }
    if (message.consistencyToken !== undefined) {
      obj.consistencyToken = ConsistencyToken.toJSON(message.consistencyToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckBulkResponse>, I>>(
    base?: I,
  ): CheckBulkResponse {
    return CheckBulkResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckBulkResponse>, I>>(
    object: I,
  ): CheckBulkResponse {
    const message = createBaseCheckBulkResponse();
    message.pairs =
      object.pairs?.map((e) => CheckBulkResponsePair.fromPartial(e)) || [];
    message.consistencyToken =
      object.consistencyToken !== undefined && object.consistencyToken !== null
        ? ConsistencyToken.fromPartial(object.consistencyToken)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
