// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/check_request.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { ResourceReference } from "./resource_reference_pb";
import { file_kessel_inventory_v1beta2_resource_reference } from "./resource_reference_pb";
import type { SubjectReference } from "./subject_reference_pb";
import { file_kessel_inventory_v1beta2_subject_reference } from "./subject_reference_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/check_request.proto.
 */
export const file_kessel_inventory_v1beta2_check_request: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CixrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvY2hlY2tfcmVxdWVzdC5wcm90bxIYa2Vzc2VsLmludmVudG9yeS52MWJldGEyIrMBCgxDaGVja1JlcXVlc3QSQwoGb2JqZWN0GAEgASgLMisua2Vzc2VsLmludmVudG9yeS52MWJldGEyLlJlc291cmNlUmVmZXJlbmNlQga6SAPIAQESGQoIcmVsYXRpb24YAiABKAlCB7pIBHICEAESQwoHc3ViamVjdBgDIAEoCzIqLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMi5TdWJqZWN0UmVmZXJlbmNlQga6SAPIAQFCcgoob3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMlABWkRnaXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMmIGcHJvdG8z",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta2_resource_reference,
      file_kessel_inventory_v1beta2_subject_reference,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta2.CheckRequest
 */
export type CheckRequest = Message<"kessel.inventory.v1beta2.CheckRequest"> & {
  /**
   * Required parameters (from an authz perspective)
   * - resource type and id
   * - permission (cannot be derived from the type as a type may have multiple 'read' permissions. Ex: https://github.com/RedHatInsights/rbac-config/blob/master/configs/prod/schemas/src/notifications.ksl#L31)
   * - user (possibly derived from an identity token)
   *
   * @generated from field: kessel.inventory.v1beta2.ResourceReference object = 1;
   */
  object?: ResourceReference;

  /**
   * @generated from field: string relation = 2;
   */
  relation: string;

  /**
   * @generated from field: kessel.inventory.v1beta2.SubjectReference subject = 3;
   */
  subject?: SubjectReference;
};

/**
 * Describes the message kessel.inventory.v1beta2.CheckRequest.
 * Use `create(CheckRequestSchema)` to create a new message.
 */
export const CheckRequestSchema: GenMessage<CheckRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_check_request, 0);
