// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/consistency.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { ConsistencyToken } from "./consistency_token_pb";
import { file_kessel_inventory_v1beta2_consistency_token } from "./consistency_token_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/consistency.proto.
 */
export const file_kessel_inventory_v1beta2_consistency: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CiprZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvY29uc2lzdGVuY3kucHJvdG8SGGtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMiKRAQoLQ29uc2lzdGVuY3kSIwoQbWluaW1pemVfbGF0ZW5jeRgBIAEoCEIHukgEagIIAUgAEkcKEWF0X2xlYXN0X2FzX2ZyZXNoGAIgASgLMioua2Vzc2VsLmludmVudG9yeS52MWJldGEyLkNvbnNpc3RlbmN5VG9rZW5IAEIUCgtyZXF1aXJlbWVudBIFukgCCAFCcgoob3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMlABWkRnaXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMmIGcHJvdG8z",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta2_consistency_token,
    ],
  );

/**
 * Defines how a request is handled by the service.
 *
 * @generated from message kessel.inventory.v1beta2.Consistency
 */
export type Consistency = Message<"kessel.inventory.v1beta2.Consistency"> & {
  /**
   * @generated from oneof kessel.inventory.v1beta2.Consistency.requirement
   */
  requirement:
    | {
        /**
         * The service selects the fastest snapshot available.
         * *Must* be set true if used.
         *
         * @generated from field: bool minimize_latency = 1;
         */
        value: boolean;
        case: "minimizeLatency";
      }
    | {
        /**
         * All data used in the API call must be *at least as fresh*
         * as found in the ConsistencyToken. More recent data might be used
         * if available or faster.
         *
         * @generated from field: kessel.inventory.v1beta2.ConsistencyToken at_least_as_fresh = 2;
         */
        value: ConsistencyToken;
        case: "atLeastAsFresh";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message kessel.inventory.v1beta2.Consistency.
 * Use `create(ConsistencySchema)` to create a new message.
 */
export const ConsistencySchema: GenMessage<Consistency> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_consistency, 0);
