// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/consistency.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { ConsistencyToken } from "./consistency_token";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * Defines how a request is handled by the service.
 * If consistency is omitted by the client, standard server configuration uses
 * minimize_latency by default, but deployments may override that default (for
 * example, to at_least_as_acknowledged).
 */
export interface Consistency {
  /**
   * The service selects the fastest snapshot available.
   * *Must* be set true if used.
   */
  minimizeLatency?: boolean | undefined;
  /**
   * All data used in the API call must be *at least as fresh*
   * as found in the ConsistencyToken. More recent data might be used
   * if available or faster.
   */
  atLeastAsFresh?: ConsistencyToken | undefined;
  /**
   * All data used in the API call must be *at least as acknowledged*,
   * meaning it includes data up to the latest write known to Inventory.
   * This aligns with `ReportResource` write visibility: when
   * `write_visibility=IMMEDIATE`, the write waits for acknowledgement, so a
   * subsequent read with `at_least_as_acknowledged` is guaranteed to be at
   * least as recent as that write.
   * Some deployments may use this behavior as the server-side default when
   * consistency is omitted.
   * *Must* be set true if used.
   */
  atLeastAsAcknowledged?: boolean | undefined;
}

function createBaseConsistency(): Consistency {
  return {
    minimizeLatency: undefined,
    atLeastAsFresh: undefined,
    atLeastAsAcknowledged: undefined,
  };
}

export const Consistency = {
  encode(
    message: Consistency,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.minimizeLatency !== undefined) {
      writer.uint32(8).bool(message.minimizeLatency);
    }
    if (message.atLeastAsFresh !== undefined) {
      ConsistencyToken.encode(
        message.atLeastAsFresh,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    if (message.atLeastAsAcknowledged !== undefined) {
      writer.uint32(24).bool(message.atLeastAsAcknowledged);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Consistency {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsistency();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.minimizeLatency = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.atLeastAsFresh = ConsistencyToken.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.atLeastAsAcknowledged = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Consistency {
    return {
      minimizeLatency: isSet(object.minimizeLatency)
        ? globalThis.Boolean(object.minimizeLatency)
        : undefined,
      atLeastAsFresh: isSet(object.atLeastAsFresh)
        ? ConsistencyToken.fromJSON(object.atLeastAsFresh)
        : undefined,
      atLeastAsAcknowledged: isSet(object.atLeastAsAcknowledged)
        ? globalThis.Boolean(object.atLeastAsAcknowledged)
        : undefined,
    };
  },

  toJSON(message: Consistency): unknown {
    const obj: any = {};
    if (message.minimizeLatency !== undefined) {
      obj.minimizeLatency = message.minimizeLatency;
    }
    if (message.atLeastAsFresh !== undefined) {
      obj.atLeastAsFresh = ConsistencyToken.toJSON(message.atLeastAsFresh);
    }
    if (message.atLeastAsAcknowledged !== undefined) {
      obj.atLeastAsAcknowledged = message.atLeastAsAcknowledged;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Consistency>, I>>(base?: I): Consistency {
    return Consistency.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Consistency>, I>>(
    object: I,
  ): Consistency {
    const message = createBaseConsistency();
    message.minimizeLatency = object.minimizeLatency ?? undefined;
    message.atLeastAsFresh =
      object.atLeastAsFresh !== undefined && object.atLeastAsFresh !== null
        ? ConsistencyToken.fromPartial(object.atLeastAsFresh)
        : undefined;
    message.atLeastAsAcknowledged = object.atLeastAsAcknowledged ?? undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
