// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/consistency_token.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/consistency_token.proto.
 */
export const file_kessel_inventory_v1beta2_consistency_token: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjBrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvY29uc2lzdGVuY3lfdG9rZW4ucHJvdG8SGGtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMiIqChBDb25zaXN0ZW5jeVRva2VuEhYKBXRva2VuGAEgASgJQge6SARyAhABQnIKKG9yZy5wcm9qZWN0X2tlc3NlbC5hcGkuaW52ZW50b3J5LnYxYmV0YTJQAVpEZ2l0aHViLmNvbS9wcm9qZWN0LWtlc3NlbC9pbnZlbnRvcnktYXBpL2FwaS9rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTJiBnByb3RvMw",
    [file_buf_validate_validate],
  );

/**
 * @generated from message kessel.inventory.v1beta2.ConsistencyToken
 */
export type ConsistencyToken =
  Message<"kessel.inventory.v1beta2.ConsistencyToken"> & {
    /**
     * @generated from field: string token = 1;
     */
    token: string;
  };

/**
 * Describes the message kessel.inventory.v1beta2.ConsistencyToken.
 * Use `create(ConsistencyTokenSchema)` to create a new message.
 */
export const ConsistencyTokenSchema: GenMessage<ConsistencyToken> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_consistency_token, 0);
