// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/create_tuples_request.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { RelationFencingCheck } from "./relation_fencing_check";
import { Relationship } from "./relationship";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: CreateTuplesRequest is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 */
export interface CreateTuplesRequest {
  /**
   * Whether or not the request should ignore existing tuples (true),
   * or if the request should fail if the same tuple already exists (false).
   * Defaults to false.
   */
  upsert?: boolean | undefined;
  tuples?: Relationship[] | undefined;
  fencingCheck?: RelationFencingCheck | undefined;
}

function createBaseCreateTuplesRequest(): CreateTuplesRequest {
  return { upsert: false, tuples: [], fencingCheck: undefined };
}

export const CreateTuplesRequest = {
  encode(
    message: CreateTuplesRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.upsert !== undefined && message.upsert !== false) {
      writer.uint32(8).bool(message.upsert);
    }
    if (message.tuples !== undefined && message.tuples.length !== 0) {
      for (const v of message.tuples) {
        Relationship.encode(v!, writer.uint32(18).fork()).ldelim();
      }
    }
    if (message.fencingCheck !== undefined) {
      RelationFencingCheck.encode(
        message.fencingCheck,
        writer.uint32(26).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateTuplesRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTuplesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.upsert = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.tuples!.push(Relationship.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.fencingCheck = RelationFencingCheck.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTuplesRequest {
    return {
      upsert: isSet(object.upsert) ? globalThis.Boolean(object.upsert) : false,
      tuples: globalThis.Array.isArray(object?.tuples)
        ? object.tuples.map((e: any) => Relationship.fromJSON(e))
        : [],
      fencingCheck: isSet(object.fencingCheck)
        ? RelationFencingCheck.fromJSON(object.fencingCheck)
        : undefined,
    };
  },

  toJSON(message: CreateTuplesRequest): unknown {
    const obj: any = {};
    if (message.upsert !== undefined && message.upsert !== false) {
      obj.upsert = message.upsert;
    }
    if (message.tuples?.length) {
      obj.tuples = message.tuples.map((e) => Relationship.toJSON(e));
    }
    if (message.fencingCheck !== undefined) {
      obj.fencingCheck = RelationFencingCheck.toJSON(message.fencingCheck);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTuplesRequest>, I>>(
    base?: I,
  ): CreateTuplesRequest {
    return CreateTuplesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTuplesRequest>, I>>(
    object: I,
  ): CreateTuplesRequest {
    const message = createBaseCreateTuplesRequest();
    message.upsert = object.upsert ?? false;
    message.tuples =
      object.tuples?.map((e) => Relationship.fromPartial(e)) || [];
    message.fencingCheck =
      object.fencingCheck !== undefined && object.fencingCheck !== null
        ? RelationFencingCheck.fromPartial(object.fencingCheck)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
