// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/delete_resource_request.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { ResourceReference } from "./resource_reference_pb";
import { file_kessel_inventory_v1beta2_resource_reference } from "./resource_reference_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/delete_resource_request.proto.
 */
export const file_kessel_inventory_v1beta2_delete_resource_request: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjZrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvZGVsZXRlX3Jlc291cmNlX3JlcXVlc3QucHJvdG8SGGtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMiJfChVEZWxldGVSZXNvdXJjZVJlcXVlc3QSRgoJcmVmZXJlbmNlGAEgASgLMisua2Vzc2VsLmludmVudG9yeS52MWJldGEyLlJlc291cmNlUmVmZXJlbmNlQga6SAPIAQFCcgoob3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMlABWkRnaXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMmIGcHJvdG8z",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta2_resource_reference,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta2.DeleteResourceRequest
 */
export type DeleteResourceRequest =
  Message<"kessel.inventory.v1beta2.DeleteResourceRequest"> & {
    /**
     * @generated from field: kessel.inventory.v1beta2.ResourceReference reference = 1;
     */
    reference?: ResourceReference;
  };

/**
 * Describes the message kessel.inventory.v1beta2.DeleteResourceRequest.
 * Use `create(DeleteResourceRequestSchema)` to create a new message.
 */
export const DeleteResourceRequestSchema: GenMessage<DeleteResourceRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_delete_resource_request, 0);
