// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/delete_resource_response.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/delete_resource_response.proto.
 */
export const file_kessel_inventory_v1beta2_delete_resource_response: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjdrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvZGVsZXRlX3Jlc291cmNlX3Jlc3BvbnNlLnByb3RvEhhrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIiGAoWRGVsZXRlUmVzb3VyY2VSZXNwb25zZUJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
  );

/**
 * @generated from message kessel.inventory.v1beta2.DeleteResourceResponse
 */
export type DeleteResourceResponse =
  Message<"kessel.inventory.v1beta2.DeleteResourceResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta2.DeleteResourceResponse.
 * Use `create(DeleteResourceResponseSchema)` to create a new message.
 */
export const DeleteResourceResponseSchema: GenMessage<DeleteResourceResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_delete_resource_response, 0);
