// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/delete_tuples_request.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { RelationFencingCheck } from "./relation_fencing_check";
import { RelationTupleFilter } from "./relation_tuple_filter";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: DeleteTuplesRequest is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 */
export interface DeleteTuplesRequest {
  filter?: RelationTupleFilter | undefined;
  fencingCheck?: RelationFencingCheck | undefined;
}

function createBaseDeleteTuplesRequest(): DeleteTuplesRequest {
  return { filter: undefined, fencingCheck: undefined };
}

export const DeleteTuplesRequest = {
  encode(
    message: DeleteTuplesRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.filter !== undefined) {
      RelationTupleFilter.encode(
        message.filter,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.fencingCheck !== undefined) {
      RelationFencingCheck.encode(
        message.fencingCheck,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DeleteTuplesRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTuplesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.filter = RelationTupleFilter.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.fencingCheck = RelationFencingCheck.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTuplesRequest {
    return {
      filter: isSet(object.filter)
        ? RelationTupleFilter.fromJSON(object.filter)
        : undefined,
      fencingCheck: isSet(object.fencingCheck)
        ? RelationFencingCheck.fromJSON(object.fencingCheck)
        : undefined,
    };
  },

  toJSON(message: DeleteTuplesRequest): unknown {
    const obj: any = {};
    if (message.filter !== undefined) {
      obj.filter = RelationTupleFilter.toJSON(message.filter);
    }
    if (message.fencingCheck !== undefined) {
      obj.fencingCheck = RelationFencingCheck.toJSON(message.fencingCheck);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTuplesRequest>, I>>(
    base?: I,
  ): DeleteTuplesRequest {
    return DeleteTuplesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTuplesRequest>, I>>(
    object: I,
  ): DeleteTuplesRequest {
    const message = createBaseDeleteTuplesRequest();
    message.filter =
      object.filter !== undefined && object.filter !== null
        ? RelationTupleFilter.fromPartial(object.filter)
        : undefined;
    message.fencingCheck =
      object.fencingCheck !== undefined && object.fencingCheck !== null
        ? RelationFencingCheck.fromPartial(object.fencingCheck)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
