// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/read_tuples_response.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { ConsistencyToken } from "./consistency_token";
import { Relationship } from "./relationship";
import { ResponsePagination } from "./response_pagination";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: ReadTuplesResponse is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 */
export interface ReadTuplesResponse {
  tuple?: Relationship | undefined;
  pagination?: ResponsePagination | undefined;
  consistencyToken?: ConsistencyToken | undefined;
}

function createBaseReadTuplesResponse(): ReadTuplesResponse {
  return {
    tuple: undefined,
    pagination: undefined,
    consistencyToken: undefined,
  };
}

export const ReadTuplesResponse = {
  encode(
    message: ReadTuplesResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.tuple !== undefined) {
      Relationship.encode(message.tuple, writer.uint32(10).fork()).ldelim();
    }
    if (message.pagination !== undefined) {
      ResponsePagination.encode(
        message.pagination,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    if (message.consistencyToken !== undefined) {
      ConsistencyToken.encode(
        message.consistencyToken,
        writer.uint32(26).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReadTuplesResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadTuplesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.tuple = Relationship.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = ResponsePagination.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.consistencyToken = ConsistencyToken.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadTuplesResponse {
    return {
      tuple: isSet(object.tuple)
        ? Relationship.fromJSON(object.tuple)
        : undefined,
      pagination: isSet(object.pagination)
        ? ResponsePagination.fromJSON(object.pagination)
        : undefined,
      consistencyToken: isSet(object.consistencyToken)
        ? ConsistencyToken.fromJSON(object.consistencyToken)
        : undefined,
    };
  },

  toJSON(message: ReadTuplesResponse): unknown {
    const obj: any = {};
    if (message.tuple !== undefined) {
      obj.tuple = Relationship.toJSON(message.tuple);
    }
    if (message.pagination !== undefined) {
      obj.pagination = ResponsePagination.toJSON(message.pagination);
    }
    if (message.consistencyToken !== undefined) {
      obj.consistencyToken = ConsistencyToken.toJSON(message.consistencyToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadTuplesResponse>, I>>(
    base?: I,
  ): ReadTuplesResponse {
    return ReadTuplesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadTuplesResponse>, I>>(
    object: I,
  ): ReadTuplesResponse {
    const message = createBaseReadTuplesResponse();
    message.tuple =
      object.tuple !== undefined && object.tuple !== null
        ? Relationship.fromPartial(object.tuple)
        : undefined;
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? ResponsePagination.fromPartial(object.pagination)
        : undefined;
    message.consistencyToken =
      object.consistencyToken !== undefined && object.consistencyToken !== null
        ? ConsistencyToken.fromPartial(object.consistencyToken)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
