// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/read_tuples_request.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Consistency } from "./consistency";
import { RelationTupleFilter } from "./relation_tuple_filter";
import { RequestPagination } from "./request_pagination";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: ReadTuplesRequest is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 */
export interface ReadTuplesRequest {
  filter?: RelationTupleFilter | undefined;
  pagination?: RequestPagination | undefined;
  consistency?: Consistency | undefined;
}

function createBaseReadTuplesRequest(): ReadTuplesRequest {
  return { filter: undefined, pagination: undefined, consistency: undefined };
}

export const ReadTuplesRequest = {
  encode(
    message: ReadTuplesRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.filter !== undefined) {
      RelationTupleFilter.encode(
        message.filter,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.pagination !== undefined) {
      RequestPagination.encode(
        message.pagination,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    if (message.consistency !== undefined) {
      Consistency.encode(
        message.consistency,
        writer.uint32(26).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReadTuplesRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadTuplesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.filter = RelationTupleFilter.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = RequestPagination.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.consistency = Consistency.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadTuplesRequest {
    return {
      filter: isSet(object.filter)
        ? RelationTupleFilter.fromJSON(object.filter)
        : undefined,
      pagination: isSet(object.pagination)
        ? RequestPagination.fromJSON(object.pagination)
        : undefined,
      consistency: isSet(object.consistency)
        ? Consistency.fromJSON(object.consistency)
        : undefined,
    };
  },

  toJSON(message: ReadTuplesRequest): unknown {
    const obj: any = {};
    if (message.filter !== undefined) {
      obj.filter = RelationTupleFilter.toJSON(message.filter);
    }
    if (message.pagination !== undefined) {
      obj.pagination = RequestPagination.toJSON(message.pagination);
    }
    if (message.consistency !== undefined) {
      obj.consistency = Consistency.toJSON(message.consistency);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadTuplesRequest>, I>>(
    base?: I,
  ): ReadTuplesRequest {
    return ReadTuplesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadTuplesRequest>, I>>(
    object: I,
  ): ReadTuplesRequest {
    const message = createBaseReadTuplesRequest();
    message.filter =
      object.filter !== undefined && object.filter !== null
        ? RelationTupleFilter.fromPartial(object.filter)
        : undefined;
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? RequestPagination.fromPartial(object.pagination)
        : undefined;
    message.consistency =
      object.consistency !== undefined && object.consistency !== null
        ? Consistency.fromPartial(object.consistency)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
