// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/relation_subject_reference.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { RelationObjectReference } from "./relation_object_reference";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: RelationSubjectReference is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 * New code should use SubjectReference instead.
 */
export interface RelationSubjectReference {
  /**
   * An optional relation which points to a set of subjects instead of the single subject.
   * e.g. "members" or "owners" of a group identified in `subject`.
   */
  relation?: string | undefined;
  subject?: RelationObjectReference | undefined;
}

function createBaseRelationSubjectReference(): RelationSubjectReference {
  return { relation: undefined, subject: undefined };
}

export const RelationSubjectReference = {
  encode(
    message: RelationSubjectReference,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.relation !== undefined) {
      writer.uint32(10).string(message.relation);
    }
    if (message.subject !== undefined) {
      RelationObjectReference.encode(
        message.subject,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): RelationSubjectReference {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelationSubjectReference();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.relation = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.subject = RelationObjectReference.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RelationSubjectReference {
    return {
      relation: isSet(object.relation)
        ? globalThis.String(object.relation)
        : undefined,
      subject: isSet(object.subject)
        ? RelationObjectReference.fromJSON(object.subject)
        : undefined,
    };
  },

  toJSON(message: RelationSubjectReference): unknown {
    const obj: any = {};
    if (message.relation !== undefined) {
      obj.relation = message.relation;
    }
    if (message.subject !== undefined) {
      obj.subject = RelationObjectReference.toJSON(message.subject);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RelationSubjectReference>, I>>(
    base?: I,
  ): RelationSubjectReference {
    return RelationSubjectReference.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RelationSubjectReference>, I>>(
    object: I,
  ): RelationSubjectReference {
    const message = createBaseRelationSubjectReference();
    message.relation = object.relation ?? undefined;
    message.subject =
      object.subject !== undefined && object.subject !== null
        ? RelationObjectReference.fromPartial(object.subject)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
