// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/relation_object_reference.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { RelationObjectType } from "./relation_object_type";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: RelationObjectReference is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 * New code should use ResourceReference instead.
 */
export interface RelationObjectReference {
  type?: RelationObjectType | undefined;
  id?: string | undefined;
}

function createBaseRelationObjectReference(): RelationObjectReference {
  return { type: undefined, id: "" };
}

export const RelationObjectReference = {
  encode(
    message: RelationObjectReference,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.type !== undefined) {
      RelationObjectType.encode(
        message.type,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(18).string(message.id);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): RelationObjectReference {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelationObjectReference();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.type = RelationObjectType.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RelationObjectReference {
    return {
      type: isSet(object.type)
        ? RelationObjectType.fromJSON(object.type)
        : undefined,
      id: isSet(object.id) ? globalThis.String(object.id) : "",
    };
  },

  toJSON(message: RelationObjectReference): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = RelationObjectType.toJSON(message.type);
    }
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RelationObjectReference>, I>>(
    base?: I,
  ): RelationObjectReference {
    return RelationObjectReference.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RelationObjectReference>, I>>(
    object: I,
  ): RelationObjectReference {
    const message = createBaseRelationObjectReference();
    message.type =
      object.type !== undefined && object.type !== null
        ? RelationObjectType.fromPartial(object.type)
        : undefined;
    message.id = object.id ?? "";
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
