// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/relation_subject_filter.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: RelationSubjectFilter is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 */
export interface RelationSubjectFilter {
  subjectNamespace?: string | undefined;
  subjectType?: string | undefined;
  subjectId?: string | undefined;
  relation?: string | undefined;
}

function createBaseRelationSubjectFilter(): RelationSubjectFilter {
  return {
    subjectNamespace: undefined,
    subjectType: undefined,
    subjectId: undefined,
    relation: undefined,
  };
}

export const RelationSubjectFilter = {
  encode(
    message: RelationSubjectFilter,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.subjectNamespace !== undefined) {
      writer.uint32(10).string(message.subjectNamespace);
    }
    if (message.subjectType !== undefined) {
      writer.uint32(18).string(message.subjectType);
    }
    if (message.subjectId !== undefined) {
      writer.uint32(26).string(message.subjectId);
    }
    if (message.relation !== undefined) {
      writer.uint32(34).string(message.relation);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): RelationSubjectFilter {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelationSubjectFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.subjectNamespace = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.subjectType = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.subjectId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.relation = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RelationSubjectFilter {
    return {
      subjectNamespace: isSet(object.subjectNamespace)
        ? globalThis.String(object.subjectNamespace)
        : undefined,
      subjectType: isSet(object.subjectType)
        ? globalThis.String(object.subjectType)
        : undefined,
      subjectId: isSet(object.subjectId)
        ? globalThis.String(object.subjectId)
        : undefined,
      relation: isSet(object.relation)
        ? globalThis.String(object.relation)
        : undefined,
    };
  },

  toJSON(message: RelationSubjectFilter): unknown {
    const obj: any = {};
    if (message.subjectNamespace !== undefined) {
      obj.subjectNamespace = message.subjectNamespace;
    }
    if (message.subjectType !== undefined) {
      obj.subjectType = message.subjectType;
    }
    if (message.subjectId !== undefined) {
      obj.subjectId = message.subjectId;
    }
    if (message.relation !== undefined) {
      obj.relation = message.relation;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RelationSubjectFilter>, I>>(
    base?: I,
  ): RelationSubjectFilter {
    return RelationSubjectFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RelationSubjectFilter>, I>>(
    object: I,
  ): RelationSubjectFilter {
    const message = createBaseRelationSubjectFilter();
    message.subjectNamespace = object.subjectNamespace ?? undefined;
    message.subjectType = object.subjectType ?? undefined;
    message.subjectId = object.subjectId ?? undefined;
    message.relation = object.relation ?? undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
