// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/relation_tuple_filter.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { RelationSubjectFilter } from "./relation_subject_filter";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: RelationTupleFilter is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 *
 * RelationTupleFilter is used to filter tuples based on their resource, relation, and subject.
 * All fields are optional but at least one field should be provided.
 */
export interface RelationTupleFilter {
  resourceNamespace?: string | undefined;
  resourceType?: string | undefined;
  resourceId?: string | undefined;
  relation?: string | undefined;
  subjectFilter?: RelationSubjectFilter | undefined;
}

function createBaseRelationTupleFilter(): RelationTupleFilter {
  return {
    resourceNamespace: undefined,
    resourceType: undefined,
    resourceId: undefined,
    relation: undefined,
    subjectFilter: undefined,
  };
}

export const RelationTupleFilter = {
  encode(
    message: RelationTupleFilter,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.resourceNamespace !== undefined) {
      writer.uint32(10).string(message.resourceNamespace);
    }
    if (message.resourceType !== undefined) {
      writer.uint32(18).string(message.resourceType);
    }
    if (message.resourceId !== undefined) {
      writer.uint32(26).string(message.resourceId);
    }
    if (message.relation !== undefined) {
      writer.uint32(34).string(message.relation);
    }
    if (message.subjectFilter !== undefined) {
      RelationSubjectFilter.encode(
        message.subjectFilter,
        writer.uint32(42).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RelationTupleFilter {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelationTupleFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.resourceNamespace = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.resourceType = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.resourceId = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.relation = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.subjectFilter = RelationSubjectFilter.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RelationTupleFilter {
    return {
      resourceNamespace: isSet(object.resourceNamespace)
        ? globalThis.String(object.resourceNamespace)
        : undefined,
      resourceType: isSet(object.resourceType)
        ? globalThis.String(object.resourceType)
        : undefined,
      resourceId: isSet(object.resourceId)
        ? globalThis.String(object.resourceId)
        : undefined,
      relation: isSet(object.relation)
        ? globalThis.String(object.relation)
        : undefined,
      subjectFilter: isSet(object.subjectFilter)
        ? RelationSubjectFilter.fromJSON(object.subjectFilter)
        : undefined,
    };
  },

  toJSON(message: RelationTupleFilter): unknown {
    const obj: any = {};
    if (message.resourceNamespace !== undefined) {
      obj.resourceNamespace = message.resourceNamespace;
    }
    if (message.resourceType !== undefined) {
      obj.resourceType = message.resourceType;
    }
    if (message.resourceId !== undefined) {
      obj.resourceId = message.resourceId;
    }
    if (message.relation !== undefined) {
      obj.relation = message.relation;
    }
    if (message.subjectFilter !== undefined) {
      obj.subjectFilter = RelationSubjectFilter.toJSON(message.subjectFilter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RelationTupleFilter>, I>>(
    base?: I,
  ): RelationTupleFilter {
    return RelationTupleFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RelationTupleFilter>, I>>(
    object: I,
  ): RelationTupleFilter {
    const message = createBaseRelationTupleFilter();
    message.resourceNamespace = object.resourceNamespace ?? undefined;
    message.resourceType = object.resourceType ?? undefined;
    message.resourceId = object.resourceId ?? undefined;
    message.relation = object.relation ?? undefined;
    message.subjectFilter =
      object.subjectFilter !== undefined && object.subjectFilter !== null
        ? RelationSubjectFilter.fromPartial(object.subjectFilter)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
