// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/relationship.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { RelationObjectReference } from "./relation_object_reference";
import { RelationSubjectReference } from "./relation_subject_reference";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: Relationship is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 * New code should use ReportResource with relationships instead.
 *
 * A Relationship is the realization of a Relation (a string)
 * between a Resource and a Subject or a Subject Set.
 */
export interface Relationship {
  resource?: RelationObjectReference | undefined;
  relation?: string | undefined;
  subject?: RelationSubjectReference | undefined;
}

function createBaseRelationship(): Relationship {
  return { resource: undefined, relation: "", subject: undefined };
}

export const Relationship = {
  encode(
    message: Relationship,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.resource !== undefined) {
      RelationObjectReference.encode(
        message.resource,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.relation !== undefined && message.relation !== "") {
      writer.uint32(18).string(message.relation);
    }
    if (message.subject !== undefined) {
      RelationSubjectReference.encode(
        message.subject,
        writer.uint32(26).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Relationship {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelationship();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.resource = RelationObjectReference.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.relation = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.subject = RelationSubjectReference.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Relationship {
    return {
      resource: isSet(object.resource)
        ? RelationObjectReference.fromJSON(object.resource)
        : undefined,
      relation: isSet(object.relation)
        ? globalThis.String(object.relation)
        : "",
      subject: isSet(object.subject)
        ? RelationSubjectReference.fromJSON(object.subject)
        : undefined,
    };
  },

  toJSON(message: Relationship): unknown {
    const obj: any = {};
    if (message.resource !== undefined) {
      obj.resource = RelationObjectReference.toJSON(message.resource);
    }
    if (message.relation !== undefined && message.relation !== "") {
      obj.relation = message.relation;
    }
    if (message.subject !== undefined) {
      obj.subject = RelationSubjectReference.toJSON(message.subject);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Relationship>, I>>(
    base?: I,
  ): Relationship {
    return Relationship.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Relationship>, I>>(
    object: I,
  ): Relationship {
    const message = createBaseRelationship();
    message.resource =
      object.resource !== undefined && object.resource !== null
        ? RelationObjectReference.fromPartial(object.resource)
        : undefined;
    message.relation = object.relation ?? "";
    message.subject =
      object.subject !== undefined && object.subject !== null
        ? RelationSubjectReference.fromPartial(object.subject)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
