// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/relation_fencing_check.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: RelationFencingCheck is part of the legacy tuple-layer API.
 * This type exists only for RBAC backward compatibility and will be removed.
 */
export interface RelationFencingCheck {
  /**
   * Note: Relations-api uses .required = true, but that doesn't enforce non-empty
   * on proto3 strings. In relations-api, empty value would fail internally anyway.
   */
  lockId?: string | undefined;
  lockToken?: string | undefined;
}

function createBaseRelationFencingCheck(): RelationFencingCheck {
  return { lockId: "", lockToken: "" };
}

export const RelationFencingCheck = {
  encode(
    message: RelationFencingCheck,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.lockId !== undefined && message.lockId !== "") {
      writer.uint32(10).string(message.lockId);
    }
    if (message.lockToken !== undefined && message.lockToken !== "") {
      writer.uint32(18).string(message.lockToken);
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): RelationFencingCheck {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelationFencingCheck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.lockId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.lockToken = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RelationFencingCheck {
    return {
      lockId: isSet(object.lockId) ? globalThis.String(object.lockId) : "",
      lockToken: isSet(object.lockToken)
        ? globalThis.String(object.lockToken)
        : "",
    };
  },

  toJSON(message: RelationFencingCheck): unknown {
    const obj: any = {};
    if (message.lockId !== undefined && message.lockId !== "") {
      obj.lockId = message.lockId;
    }
    if (message.lockToken !== undefined && message.lockToken !== "") {
      obj.lockToken = message.lockToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RelationFencingCheck>, I>>(
    base?: I,
  ): RelationFencingCheck {
    return RelationFencingCheck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RelationFencingCheck>, I>>(
    object: I,
  ): RelationFencingCheck {
    const message = createBaseRelationFencingCheck();
    message.lockId = object.lockId ?? "";
    message.lockToken = object.lockToken ?? "";
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
