// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/reporter_reference.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/reporter_reference.proto.
 */
export const file_kessel_inventory_v1beta2_reporter_reference: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjFrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvcmVwb3J0ZXJfcmVmZXJlbmNlLnByb3RvEhhrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIiVAoRUmVwb3J0ZXJSZWZlcmVuY2USFQoEdHlwZRgBIAEoCUIHukgEcgIQARIYCgtpbnN0YW5jZV9pZBgCIAEoCUgAiAEBQg4KDF9pbnN0YW5jZV9pZEJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
    [file_buf_validate_validate],
  );

/**
 * @generated from message kessel.inventory.v1beta2.ReporterReference
 */
export type ReporterReference =
  Message<"kessel.inventory.v1beta2.ReporterReference"> & {
    /**
     * @generated from field: string type = 1;
     */
    type: string;

    /**
     * @generated from field: optional string instance_id = 2;
     */
    instanceId?: string;
  };

/**
 * Describes the message kessel.inventory.v1beta2.ReporterReference.
 * Use `create(ReporterReferenceSchema)` to create a new message.
 */
export const ReporterReferenceSchema: GenMessage<ReporterReference> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_reporter_reference, 0);
