// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/report_resource_response.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/report_resource_response.proto.
 */
export const file_kessel_inventory_v1beta2_report_resource_response: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjdrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvcmVwb3J0X3Jlc291cmNlX3Jlc3BvbnNlLnByb3RvEhhrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIiGAoWUmVwb3J0UmVzb3VyY2VSZXNwb25zZUJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
  );

/**
 * @generated from message kessel.inventory.v1beta2.ReportResourceResponse
 */
export type ReportResourceResponse =
  Message<"kessel.inventory.v1beta2.ReportResourceResponse"> & {};

/**
 * Describes the message kessel.inventory.v1beta2.ReportResourceResponse.
 * Use `create(ReportResourceResponseSchema)` to create a new message.
 */
export const ReportResourceResponseSchema: GenMessage<ReportResourceResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_report_resource_response, 0);
