// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/representation_type.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/representation_type.proto.
 */
export const file_kessel_inventory_v1beta2_representation_type: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjJrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvcmVwcmVzZW50YXRpb25fdHlwZS5wcm90bxIYa2Vzc2VsLmludmVudG9yeS52MWJldGEyImIKElJlcHJlc2VudGF0aW9uVHlwZRIeCg1yZXNvdXJjZV90eXBlGAEgASgJQge6SARyAhABEhoKDXJlcG9ydGVyX3R5cGUYAiABKAlIAIgBAUIQCg5fcmVwb3J0ZXJfdHlwZUJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
    [file_buf_validate_validate],
  );

/**
 * @generated from message kessel.inventory.v1beta2.RepresentationType
 */
export type RepresentationType =
  Message<"kessel.inventory.v1beta2.RepresentationType"> & {
    /**
     * @generated from field: string resource_type = 1;
     */
    resourceType: string;

    /**
     * @generated from field: optional string reporter_type = 2;
     */
    reporterType?: string;
  };

/**
 * Describes the message kessel.inventory.v1beta2.RepresentationType.
 * Use `create(RepresentationTypeSchema)` to create a new message.
 */
export const RepresentationTypeSchema: GenMessage<RepresentationType> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_representation_type, 0);
