// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/representation_metadata.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/representation_metadata.proto.
 */
export const file_kessel_inventory_v1beta2_representation_metadata: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjZrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvcmVwcmVzZW50YXRpb25fbWV0YWRhdGEucHJvdG8SGGtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMiK3AQoWUmVwcmVzZW50YXRpb25NZXRhZGF0YRIiChFsb2NhbF9yZXNvdXJjZV9pZBgBIAEoCUIHukgEcgIQARIZCghhcGlfaHJlZhgCIAEoCUIHukgEcgIQARIZCgxjb25zb2xlX2hyZWYYAyABKAlIAIgBARIdChByZXBvcnRlcl92ZXJzaW9uGAQgASgJSAGIAQFCDwoNX2NvbnNvbGVfaHJlZkITChFfcmVwb3J0ZXJfdmVyc2lvbkJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
    [file_buf_validate_validate],
  );

/**
 * @generated from message kessel.inventory.v1beta2.RepresentationMetadata
 */
export type RepresentationMetadata =
  Message<"kessel.inventory.v1beta2.RepresentationMetadata"> & {
    /**
     * @generated from field: string local_resource_id = 1;
     */
    localResourceId: string;

    /**
     * @generated from field: string api_href = 2;
     */
    apiHref: string;

    /**
     * @generated from field: optional string console_href = 3;
     */
    consoleHref?: string;

    /**
     * @generated from field: optional string reporter_version = 4;
     */
    reporterVersion?: string;
  };

/**
 * Describes the message kessel.inventory.v1beta2.RepresentationMetadata.
 * Use `create(RepresentationMetadataSchema)` to create a new message.
 */
export const RepresentationMetadataSchema: GenMessage<RepresentationMetadata> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_representation_metadata, 0);
