// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/request_pagination.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/request_pagination.proto.
 */
export const file_kessel_inventory_v1beta2_request_pagination: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjFrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvcmVxdWVzdF9wYWdpbmF0aW9uLnByb3RvEhhrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIiYwoRUmVxdWVzdFBhZ2luYXRpb24SFgoFbGltaXQYASABKA1CB7pIBCoCIAASHwoSY29udGludWF0aW9uX3Rva2VuGAIgASgJSACIAQFCFQoTX2NvbnRpbnVhdGlvbl90b2tlbkJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
    [file_buf_validate_validate],
  );

/**
 * @generated from message kessel.inventory.v1beta2.RequestPagination
 */
export type RequestPagination =
  Message<"kessel.inventory.v1beta2.RequestPagination"> & {
    /**
     * @generated from field: uint32 limit = 1;
     */
    limit: number;

    /**
     * @generated from field: optional string continuation_token = 2;
     */
    continuationToken?: string;
  };

/**
 * Describes the message kessel.inventory.v1beta2.RequestPagination.
 * Use `create(RequestPaginationSchema)` to create a new message.
 */
export const RequestPaginationSchema: GenMessage<RequestPagination> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_request_pagination, 0);
