// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/resource_representations.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { RepresentationMetadata } from "./representation_metadata_pb";
import { file_kessel_inventory_v1beta2_representation_metadata } from "./representation_metadata_pb";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/resource_representations.proto.
 */
export const file_kessel_inventory_v1beta2_resource_representations: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjdrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvcmVzb3VyY2VfcmVwcmVzZW50YXRpb25zLnByb3RvEhhrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIi2wEKF1Jlc291cmNlUmVwcmVzZW50YXRpb25zEkoKCG1ldGFkYXRhGAEgASgLMjAua2Vzc2VsLmludmVudG9yeS52MWJldGEyLlJlcHJlc2VudGF0aW9uTWV0YWRhdGFCBrpIA8gBARIsCgZjb21tb24YAiABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0SACIAQESLgoIcmVwb3J0ZXIYAyABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0SAGIAQFCCQoHX2NvbW1vbkILCglfcmVwb3J0ZXJCcgoob3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMlABWkRnaXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMmIGcHJvdG8z",
    [
      file_google_protobuf_struct,
      file_kessel_inventory_v1beta2_representation_metadata,
      file_buf_validate_validate,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta2.ResourceRepresentations
 */
export type ResourceRepresentations =
  Message<"kessel.inventory.v1beta2.ResourceRepresentations"> & {
    /**
     * @generated from field: kessel.inventory.v1beta2.RepresentationMetadata metadata = 1;
     */
    metadata?: RepresentationMetadata;

    /**
     * @generated from field: optional google.protobuf.Struct common = 2;
     */
    common?: JsonObject;

    /**
     * @generated from field: optional google.protobuf.Struct reporter = 3;
     */
    reporter?: JsonObject;
  };

/**
 * Describes the message kessel.inventory.v1beta2.ResourceRepresentations.
 * Use `create(ResourceRepresentationsSchema)` to create a new message.
 */
export const ResourceRepresentationsSchema: GenMessage<ResourceRepresentations> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_resource_representations, 0);
