// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/resource_reference.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { ReporterReference } from "./reporter_reference_pb";
import { file_kessel_inventory_v1beta2_reporter_reference } from "./reporter_reference_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/resource_reference.proto.
 */
export const file_kessel_inventory_v1beta2_resource_reference: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjFrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvcmVzb3VyY2VfcmVmZXJlbmNlLnByb3RvEhhrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIioQEKEVJlc291cmNlUmVmZXJlbmNlEh0KDXJlc291cmNlX3R5cGUYASABKAlCBrpIA8gBARIcCgtyZXNvdXJjZV9pZBgCIAEoCUIHukgEcgIQARJCCghyZXBvcnRlchgDIAEoCzIrLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMi5SZXBvcnRlclJlZmVyZW5jZUgAiAEBQgsKCV9yZXBvcnRlckJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta2_reporter_reference,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta2.ResourceReference
 */
export type ResourceReference =
  Message<"kessel.inventory.v1beta2.ResourceReference"> & {
    /**
     * @generated from field: string resource_type = 1;
     */
    resourceType: string;

    /**
     * @generated from field: string resource_id = 2;
     */
    resourceId: string;

    /**
     * @generated from field: optional kessel.inventory.v1beta2.ReporterReference reporter = 3;
     */
    reporter?: ReporterReference;
  };

/**
 * Describes the message kessel.inventory.v1beta2.ResourceReference.
 * Use `create(ResourceReferenceSchema)` to create a new message.
 */
export const ResourceReferenceSchema: GenMessage<ResourceReference> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_resource_reference, 0);
