// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/response_pagination.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/response_pagination.proto.
 */
export const file_kessel_inventory_v1beta2_response_pagination: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjJrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvcmVzcG9uc2VfcGFnaW5hdGlvbi5wcm90bxIYa2Vzc2VsLmludmVudG9yeS52MWJldGEyIjAKElJlc3BvbnNlUGFnaW5hdGlvbhIaChJjb250aW51YXRpb25fdG9rZW4YASABKAlCcgoob3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMlABWkRnaXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMmIGcHJvdG8z",
  );

/**
 * @generated from message kessel.inventory.v1beta2.ResponsePagination
 */
export type ResponsePagination =
  Message<"kessel.inventory.v1beta2.ResponsePagination"> & {
    /**
     * @generated from field: string continuation_token = 1;
     */
    continuationToken: string;
  };

/**
 * Describes the message kessel.inventory.v1beta2.ResponsePagination.
 * Use `create(ResponsePaginationSchema)` to create a new message.
 */
export const ResponsePaginationSchema: GenMessage<ResponsePagination> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_response_pagination, 0);
