// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/streamed_list_objects_request.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { RequestPagination } from "./request_pagination_pb";
import { file_kessel_inventory_v1beta2_request_pagination } from "./request_pagination_pb";
import type { SubjectReference } from "./subject_reference_pb";
import { file_kessel_inventory_v1beta2_subject_reference } from "./subject_reference_pb";
import type { Consistency } from "./consistency_pb";
import { file_kessel_inventory_v1beta2_consistency } from "./consistency_pb";
import type { RepresentationType } from "./representation_type_pb";
import { file_kessel_inventory_v1beta2_representation_type } from "./representation_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/streamed_list_objects_request.proto.
 */
export const file_kessel_inventory_v1beta2_streamed_list_objects_request: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjxrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvc3RyZWFtZWRfbGlzdF9vYmplY3RzX3JlcXVlc3QucHJvdG8SGGtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMiLtAgoaU3RyZWFtZWRMaXN0T2JqZWN0c1JlcXVlc3QSSQoLb2JqZWN0X3R5cGUYASABKAsyLC5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIuUmVwcmVzZW50YXRpb25UeXBlQga6SAPIAQESGQoIcmVsYXRpb24YAiABKAlCB7pIBHICEAESQwoHc3ViamVjdBgDIAEoCzIqLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMi5TdWJqZWN0UmVmZXJlbmNlQga6SAPIAQESRAoKcGFnaW5hdGlvbhgEIAEoCzIrLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMi5SZXF1ZXN0UGFnaW5hdGlvbkgAiAEBEj8KC2NvbnNpc3RlbmN5GAUgASgLMiUua2Vzc2VsLmludmVudG9yeS52MWJldGEyLkNvbnNpc3RlbmN5SAGIAQFCDQoLX3BhZ2luYXRpb25CDgoMX2NvbnNpc3RlbmN5QnIKKG9yZy5wcm9qZWN0X2tlc3NlbC5hcGkuaW52ZW50b3J5LnYxYmV0YTJQAVpEZ2l0aHViLmNvbS9wcm9qZWN0LWtlc3NlbC9pbnZlbnRvcnktYXBpL2FwaS9rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTJiBnByb3RvMw",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta2_request_pagination,
      file_kessel_inventory_v1beta2_subject_reference,
      file_kessel_inventory_v1beta2_consistency,
      file_kessel_inventory_v1beta2_representation_type,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta2.StreamedListObjectsRequest
 */
export type StreamedListObjectsRequest =
  Message<"kessel.inventory.v1beta2.StreamedListObjectsRequest"> & {
    /**
     * @generated from field: kessel.inventory.v1beta2.RepresentationType object_type = 1;
     */
    objectType?: RepresentationType;

    /**
     * @generated from field: string relation = 2;
     */
    relation: string;

    /**
     * @generated from field: kessel.inventory.v1beta2.SubjectReference subject = 3;
     */
    subject?: SubjectReference;

    /**
     * @generated from field: optional kessel.inventory.v1beta2.RequestPagination pagination = 4;
     */
    pagination?: RequestPagination;

    /**
     * @generated from field: optional kessel.inventory.v1beta2.Consistency consistency = 5;
     */
    consistency?: Consistency;
  };

/**
 * Describes the message kessel.inventory.v1beta2.StreamedListObjectsRequest.
 * Use `create(StreamedListObjectsRequestSchema)` to create a new message.
 */
export const StreamedListObjectsRequestSchema: GenMessage<StreamedListObjectsRequest> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_streamed_list_objects_request, 0);
