// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/streamed_list_subjects_request.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Consistency } from "./consistency";
import { RepresentationType } from "./representation_type";
import { RequestPagination } from "./request_pagination";
import { ResourceReference } from "./resource_reference";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * StreamedListSubjectsRequest finds subjects that have a specific relation to a resource.
 * This answers the question: "Which subjects of type X have relation Y to resource Z?"
 */
export interface StreamedListSubjectsRequest {
  resource?: ResourceReference | undefined;
  relation?: string | undefined;
  subjectType?: RepresentationType | undefined;
  subjectRelation?: string | undefined;
  pagination?: RequestPagination | undefined;
  consistency?: Consistency | undefined;
}

function createBaseStreamedListSubjectsRequest(): StreamedListSubjectsRequest {
  return {
    resource: undefined,
    relation: "",
    subjectType: undefined,
    subjectRelation: undefined,
    pagination: undefined,
    consistency: undefined,
  };
}

export const StreamedListSubjectsRequest = {
  encode(
    message: StreamedListSubjectsRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.resource !== undefined) {
      ResourceReference.encode(
        message.resource,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.relation !== undefined && message.relation !== "") {
      writer.uint32(18).string(message.relation);
    }
    if (message.subjectType !== undefined) {
      RepresentationType.encode(
        message.subjectType,
        writer.uint32(26).fork(),
      ).ldelim();
    }
    if (message.subjectRelation !== undefined) {
      writer.uint32(34).string(message.subjectRelation);
    }
    if (message.pagination !== undefined) {
      RequestPagination.encode(
        message.pagination,
        writer.uint32(42).fork(),
      ).ldelim();
    }
    if (message.consistency !== undefined) {
      Consistency.encode(
        message.consistency,
        writer.uint32(50).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): StreamedListSubjectsRequest {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamedListSubjectsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.resource = ResourceReference.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.relation = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.subjectType = RepresentationType.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.subjectRelation = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.pagination = RequestPagination.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.consistency = Consistency.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamedListSubjectsRequest {
    return {
      resource: isSet(object.resource)
        ? ResourceReference.fromJSON(object.resource)
        : undefined,
      relation: isSet(object.relation)
        ? globalThis.String(object.relation)
        : "",
      subjectType: isSet(object.subjectType)
        ? RepresentationType.fromJSON(object.subjectType)
        : undefined,
      subjectRelation: isSet(object.subjectRelation)
        ? globalThis.String(object.subjectRelation)
        : undefined,
      pagination: isSet(object.pagination)
        ? RequestPagination.fromJSON(object.pagination)
        : undefined,
      consistency: isSet(object.consistency)
        ? Consistency.fromJSON(object.consistency)
        : undefined,
    };
  },

  toJSON(message: StreamedListSubjectsRequest): unknown {
    const obj: any = {};
    if (message.resource !== undefined) {
      obj.resource = ResourceReference.toJSON(message.resource);
    }
    if (message.relation !== undefined && message.relation !== "") {
      obj.relation = message.relation;
    }
    if (message.subjectType !== undefined) {
      obj.subjectType = RepresentationType.toJSON(message.subjectType);
    }
    if (message.subjectRelation !== undefined) {
      obj.subjectRelation = message.subjectRelation;
    }
    if (message.pagination !== undefined) {
      obj.pagination = RequestPagination.toJSON(message.pagination);
    }
    if (message.consistency !== undefined) {
      obj.consistency = Consistency.toJSON(message.consistency);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamedListSubjectsRequest>, I>>(
    base?: I,
  ): StreamedListSubjectsRequest {
    return StreamedListSubjectsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamedListSubjectsRequest>, I>>(
    object: I,
  ): StreamedListSubjectsRequest {
    const message = createBaseStreamedListSubjectsRequest();
    message.resource =
      object.resource !== undefined && object.resource !== null
        ? ResourceReference.fromPartial(object.resource)
        : undefined;
    message.relation = object.relation ?? "";
    message.subjectType =
      object.subjectType !== undefined && object.subjectType !== null
        ? RepresentationType.fromPartial(object.subjectType)
        : undefined;
    message.subjectRelation = object.subjectRelation ?? undefined;
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? RequestPagination.fromPartial(object.pagination)
        : undefined;
    message.consistency =
      object.consistency !== undefined && object.consistency !== null
        ? Consistency.fromPartial(object.consistency)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
