// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/streamed_list_subjects_response.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { ConsistencyToken } from "./consistency_token";
import { ResponsePagination } from "./response_pagination";
import { SubjectReference } from "./subject_reference";

export const protobufPackage = "kessel.inventory.v1beta2";

export interface StreamedListSubjectsResponse {
  subject?: SubjectReference | undefined;
  pagination?: ResponsePagination | undefined;
  consistencyToken?: ConsistencyToken | undefined;
}

function createBaseStreamedListSubjectsResponse(): StreamedListSubjectsResponse {
  return {
    subject: undefined,
    pagination: undefined,
    consistencyToken: undefined,
  };
}

export const StreamedListSubjectsResponse = {
  encode(
    message: StreamedListSubjectsResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.subject !== undefined) {
      SubjectReference.encode(
        message.subject,
        writer.uint32(10).fork(),
      ).ldelim();
    }
    if (message.pagination !== undefined) {
      ResponsePagination.encode(
        message.pagination,
        writer.uint32(18).fork(),
      ).ldelim();
    }
    if (message.consistencyToken !== undefined) {
      ConsistencyToken.encode(
        message.consistencyToken,
        writer.uint32(26).fork(),
      ).ldelim();
    }
    return writer;
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): StreamedListSubjectsResponse {
    const reader =
      input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamedListSubjectsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.subject = SubjectReference.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = ResponsePagination.decode(
            reader,
            reader.uint32(),
          );
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.consistencyToken = ConsistencyToken.decode(
            reader,
            reader.uint32(),
          );
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamedListSubjectsResponse {
    return {
      subject: isSet(object.subject)
        ? SubjectReference.fromJSON(object.subject)
        : undefined,
      pagination: isSet(object.pagination)
        ? ResponsePagination.fromJSON(object.pagination)
        : undefined,
      consistencyToken: isSet(object.consistencyToken)
        ? ConsistencyToken.fromJSON(object.consistencyToken)
        : undefined,
    };
  },

  toJSON(message: StreamedListSubjectsResponse): unknown {
    const obj: any = {};
    if (message.subject !== undefined) {
      obj.subject = SubjectReference.toJSON(message.subject);
    }
    if (message.pagination !== undefined) {
      obj.pagination = ResponsePagination.toJSON(message.pagination);
    }
    if (message.consistencyToken !== undefined) {
      obj.consistencyToken = ConsistencyToken.toJSON(message.consistencyToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamedListSubjectsResponse>, I>>(
    base?: I,
  ): StreamedListSubjectsResponse {
    return StreamedListSubjectsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamedListSubjectsResponse>, I>>(
    object: I,
  ): StreamedListSubjectsResponse {
    const message = createBaseStreamedListSubjectsResponse();
    message.subject =
      object.subject !== undefined && object.subject !== null
        ? SubjectReference.fromPartial(object.subject)
        : undefined;
    message.pagination =
      object.pagination !== undefined && object.pagination !== null
        ? ResponsePagination.fromPartial(object.pagination)
        : undefined;
    message.consistencyToken =
      object.consistencyToken !== undefined && object.consistencyToken !== null
        ? ConsistencyToken.fromPartial(object.consistencyToken)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
