// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/streamed_list_objects_response.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ResourceReference } from "./resource_reference_pb";
import { file_kessel_inventory_v1beta2_resource_reference } from "./resource_reference_pb";
import type { ResponsePagination } from "./response_pagination_pb";
import { file_kessel_inventory_v1beta2_response_pagination } from "./response_pagination_pb";
import type { ConsistencyToken } from "./consistency_token_pb";
import { file_kessel_inventory_v1beta2_consistency_token } from "./consistency_token_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/streamed_list_objects_response.proto.
 */
export const file_kessel_inventory_v1beta2_streamed_list_objects_response: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Cj1rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvc3RyZWFtZWRfbGlzdF9vYmplY3RzX3Jlc3BvbnNlLnByb3RvEhhrZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIi4wEKG1N0cmVhbWVkTGlzdE9iamVjdHNSZXNwb25zZRI7CgZvYmplY3QYASABKAsyKy5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIuUmVzb3VyY2VSZWZlcmVuY2USQAoKcGFnaW5hdGlvbhgCIAEoCzIsLmtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMi5SZXNwb25zZVBhZ2luYXRpb24SRQoRY29uc2lzdGVuY3lfdG9rZW4YAyABKAsyKi5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIuQ29uc2lzdGVuY3lUb2tlbkJyCihvcmcucHJvamVjdF9rZXNzZWwuYXBpLmludmVudG9yeS52MWJldGEyUAFaRGdpdGh1Yi5jb20vcHJvamVjdC1rZXNzZWwvaW52ZW50b3J5LWFwaS9hcGkva2Vzc2VsL2ludmVudG9yeS92MWJldGEyYgZwcm90bzM",
    [
      file_kessel_inventory_v1beta2_resource_reference,
      file_kessel_inventory_v1beta2_response_pagination,
      file_kessel_inventory_v1beta2_consistency_token,
    ],
  );

/**
 * @generated from message kessel.inventory.v1beta2.StreamedListObjectsResponse
 */
export type StreamedListObjectsResponse =
  Message<"kessel.inventory.v1beta2.StreamedListObjectsResponse"> & {
    /**
     * @generated from field: kessel.inventory.v1beta2.ResourceReference object = 1;
     */
    object?: ResourceReference;

    /**
     * @generated from field: kessel.inventory.v1beta2.ResponsePagination pagination = 2;
     */
    pagination?: ResponsePagination;

    /**
     * @generated from field: kessel.inventory.v1beta2.ConsistencyToken consistency_token = 3;
     */
    consistencyToken?: ConsistencyToken;
  };

/**
 * Describes the message kessel.inventory.v1beta2.StreamedListObjectsResponse.
 * Use `create(StreamedListObjectsResponseSchema)` to create a new message.
 */
export const StreamedListObjectsResponseSchema: GenMessage<StreamedListObjectsResponse> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_streamed_list_objects_response, 0);
