// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/subject_reference.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { ResourceReference } from "./resource_reference_pb";
import { file_kessel_inventory_v1beta2_resource_reference } from "./resource_reference_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kessel/inventory/v1beta2/subject_reference.proto.
 */
export const file_kessel_inventory_v1beta2_subject_reference: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CjBrZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvc3ViamVjdF9yZWZlcmVuY2UucHJvdG8SGGtlc3NlbC5pbnZlbnRvcnkudjFiZXRhMiJ9ChBTdWJqZWN0UmVmZXJlbmNlEhUKCHJlbGF0aW9uGAEgASgJSACIAQESRQoIcmVzb3VyY2UYAiABKAsyKy5rZXNzZWwuaW52ZW50b3J5LnYxYmV0YTIuUmVzb3VyY2VSZWZlcmVuY2VCBrpIA8gBAUILCglfcmVsYXRpb25Ccgoob3JnLnByb2plY3Rfa2Vzc2VsLmFwaS5pbnZlbnRvcnkudjFiZXRhMlABWkRnaXRodWIuY29tL3Byb2plY3Qta2Vzc2VsL2ludmVudG9yeS1hcGkvYXBpL2tlc3NlbC9pbnZlbnRvcnkvdjFiZXRhMmIGcHJvdG8z",
    [
      file_buf_validate_validate,
      file_kessel_inventory_v1beta2_resource_reference,
    ],
  );

/**
 * A reference to a Subject or, if a `relation` is provided, a Subject Set.
 *
 * @generated from message kessel.inventory.v1beta2.SubjectReference
 */
export type SubjectReference =
  Message<"kessel.inventory.v1beta2.SubjectReference"> & {
    /**
     * An optional relation which points to a set of Subjects instead of the single Subject.
     * e.g. "members" or "owners" of a group identified in `subject`.
     *
     * @generated from field: optional string relation = 1;
     */
    relation?: string;

    /**
     * @generated from field: kessel.inventory.v1beta2.ResourceReference resource = 2;
     */
    resource?: ResourceReference;
  };

/**
 * Describes the message kessel.inventory.v1beta2.SubjectReference.
 * Use `create(SubjectReferenceSchema)` to create a new message.
 */
export const SubjectReferenceSchema: GenMessage<SubjectReference> =
  /*@__PURE__*/
  messageDesc(file_kessel_inventory_v1beta2_subject_reference, 0);
