// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kessel/inventory/v1beta2/tuple_service.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  ClientReadableStream,
  type ClientUnaryCall,
  handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { AcquireLockRequest } from "./acquire_lock_request";
import { AcquireLockResponse } from "./acquire_lock_response";
import { CreateTuplesRequest } from "./create_tuples_request";
import { CreateTuplesResponse } from "./create_tuples_response";
import { DeleteTuplesRequest } from "./delete_tuples_request";
import { DeleteTuplesResponse } from "./delete_tuples_response";
import { ReadTuplesRequest } from "./read_tuples_request";
import { ReadTuplesResponse } from "./read_tuples_response";

export const protobufPackage = "kessel.inventory.v1beta2";

/**
 * DEPRECATED: KesselTupleService provides legacy tuple-layer operations.
 * This service exists only for RBAC backward compatibility and will be removed.
 * All endpoints are marked deprecated. Do not add new consumers.
 * Use KesselInventoryService's ReportResource for new integrations.
 */
export type KesselTupleServiceDefinition = typeof KesselTupleServiceDefinition;
export const KesselTupleServiceDefinition = {
  name: "KesselTupleService",
  fullName: "kessel.inventory.v1beta2.KesselTupleService",
  methods: {
    /**
     * DEPRECATED: CreateTuples creates relationship tuples.
     * This endpoint exists only for RBAC backward compatibility.
     * Use ReportResource instead for new code.
     *
     * @deprecated
     */
    createTuples: {
      name: "CreateTuples",
      requestType: CreateTuplesRequest,
      requestStream: false,
      responseType: CreateTuplesResponse,
      responseStream: false,
      options: {},
    },
    /**
     * DEPRECATED: DeleteTuples deletes relationship tuples.
     * This endpoint exists only for RBAC backward compatibility.
     * Use DeleteResource instead for new code.
     *
     * @deprecated
     */
    deleteTuples: {
      name: "DeleteTuples",
      requestType: DeleteTuplesRequest,
      requestStream: false,
      responseType: DeleteTuplesResponse,
      responseStream: false,
      options: {},
    },
    /**
     * DEPRECATED: ReadTuples reads relationship tuples.
     * This endpoint exists only for RBAC backward compatibility.
     * Use StreamedListObjects/StreamedListSubjects instead for new code.
     *
     * @deprecated
     */
    readTuples: {
      name: "ReadTuples",
      requestType: ReadTuplesRequest,
      requestStream: false,
      responseType: ReadTuplesResponse,
      responseStream: true,
      options: {},
    },
    /**
     * DEPRECATED: AcquireLock acquires a distributed lock.
     * This endpoint exists only for RBAC backward compatibility.
     *
     * @deprecated
     */
    acquireLock: {
      name: "AcquireLock",
      requestType: AcquireLockRequest,
      requestStream: false,
      responseType: AcquireLockResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

/**
 * DEPRECATED: KesselTupleService provides legacy tuple-layer operations.
 * This service exists only for RBAC backward compatibility and will be removed.
 * All endpoints are marked deprecated. Do not add new consumers.
 * Use KesselInventoryService's ReportResource for new integrations.
 */
export type KesselTupleServiceService = typeof KesselTupleServiceService;
export const KesselTupleServiceService = {
  /**
   * DEPRECATED: CreateTuples creates relationship tuples.
   * This endpoint exists only for RBAC backward compatibility.
   * Use ReportResource instead for new code.
   *
   * @deprecated
   */
  createTuples: {
    path: "/kessel.inventory.v1beta2.KesselTupleService/CreateTuples",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateTuplesRequest) =>
      Buffer.from(CreateTuplesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CreateTuplesRequest.decode(value),
    responseSerialize: (value: CreateTuplesResponse) =>
      Buffer.from(CreateTuplesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CreateTuplesResponse.decode(value),
  },
  /**
   * DEPRECATED: DeleteTuples deletes relationship tuples.
   * This endpoint exists only for RBAC backward compatibility.
   * Use DeleteResource instead for new code.
   *
   * @deprecated
   */
  deleteTuples: {
    path: "/kessel.inventory.v1beta2.KesselTupleService/DeleteTuples",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteTuplesRequest) =>
      Buffer.from(DeleteTuplesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => DeleteTuplesRequest.decode(value),
    responseSerialize: (value: DeleteTuplesResponse) =>
      Buffer.from(DeleteTuplesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => DeleteTuplesResponse.decode(value),
  },
  /**
   * DEPRECATED: ReadTuples reads relationship tuples.
   * This endpoint exists only for RBAC backward compatibility.
   * Use StreamedListObjects/StreamedListSubjects instead for new code.
   *
   * @deprecated
   */
  readTuples: {
    path: "/kessel.inventory.v1beta2.KesselTupleService/ReadTuples",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: ReadTuplesRequest) =>
      Buffer.from(ReadTuplesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ReadTuplesRequest.decode(value),
    responseSerialize: (value: ReadTuplesResponse) =>
      Buffer.from(ReadTuplesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ReadTuplesResponse.decode(value),
  },
  /**
   * DEPRECATED: AcquireLock acquires a distributed lock.
   * This endpoint exists only for RBAC backward compatibility.
   *
   * @deprecated
   */
  acquireLock: {
    path: "/kessel.inventory.v1beta2.KesselTupleService/AcquireLock",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AcquireLockRequest) =>
      Buffer.from(AcquireLockRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AcquireLockRequest.decode(value),
    responseSerialize: (value: AcquireLockResponse) =>
      Buffer.from(AcquireLockResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => AcquireLockResponse.decode(value),
  },
} as const;

export interface KesselTupleServiceServer extends UntypedServiceImplementation {
  /**
   * DEPRECATED: CreateTuples creates relationship tuples.
   * This endpoint exists only for RBAC backward compatibility.
   * Use ReportResource instead for new code.
   *
   * @deprecated
   */
  createTuples: handleUnaryCall<CreateTuplesRequest, CreateTuplesResponse>;
  /**
   * DEPRECATED: DeleteTuples deletes relationship tuples.
   * This endpoint exists only for RBAC backward compatibility.
   * Use DeleteResource instead for new code.
   *
   * @deprecated
   */
  deleteTuples: handleUnaryCall<DeleteTuplesRequest, DeleteTuplesResponse>;
  /**
   * DEPRECATED: ReadTuples reads relationship tuples.
   * This endpoint exists only for RBAC backward compatibility.
   * Use StreamedListObjects/StreamedListSubjects instead for new code.
   *
   * @deprecated
   */
  readTuples: handleServerStreamingCall<ReadTuplesRequest, ReadTuplesResponse>;
  /**
   * DEPRECATED: AcquireLock acquires a distributed lock.
   * This endpoint exists only for RBAC backward compatibility.
   *
   * @deprecated
   */
  acquireLock: handleUnaryCall<AcquireLockRequest, AcquireLockResponse>;
}

export interface KesselTupleServiceClient extends Client {
  /**
   * DEPRECATED: CreateTuples creates relationship tuples.
   * This endpoint exists only for RBAC backward compatibility.
   * Use ReportResource instead for new code.
   *
   * @deprecated
   */
  createTuples(
    request: CreateTuplesRequest,
    callback: (
      error: ServiceError | null,
      response: CreateTuplesResponse,
    ) => void,
  ): ClientUnaryCall;
  createTuples(
    request: CreateTuplesRequest,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: CreateTuplesResponse,
    ) => void,
  ): ClientUnaryCall;
  createTuples(
    request: CreateTuplesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: CreateTuplesResponse,
    ) => void,
  ): ClientUnaryCall;
  /**
   * DEPRECATED: DeleteTuples deletes relationship tuples.
   * This endpoint exists only for RBAC backward compatibility.
   * Use DeleteResource instead for new code.
   *
   * @deprecated
   */
  deleteTuples(
    request: DeleteTuplesRequest,
    callback: (
      error: ServiceError | null,
      response: DeleteTuplesResponse,
    ) => void,
  ): ClientUnaryCall;
  deleteTuples(
    request: DeleteTuplesRequest,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: DeleteTuplesResponse,
    ) => void,
  ): ClientUnaryCall;
  deleteTuples(
    request: DeleteTuplesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: DeleteTuplesResponse,
    ) => void,
  ): ClientUnaryCall;
  /**
   * DEPRECATED: ReadTuples reads relationship tuples.
   * This endpoint exists only for RBAC backward compatibility.
   * Use StreamedListObjects/StreamedListSubjects instead for new code.
   *
   * @deprecated
   */
  readTuples(
    request: ReadTuplesRequest,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<ReadTuplesResponse>;
  readTuples(
    request: ReadTuplesRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<ReadTuplesResponse>;
  /**
   * DEPRECATED: AcquireLock acquires a distributed lock.
   * This endpoint exists only for RBAC backward compatibility.
   *
   * @deprecated
   */
  acquireLock(
    request: AcquireLockRequest,
    callback: (
      error: ServiceError | null,
      response: AcquireLockResponse,
    ) => void,
  ): ClientUnaryCall;
  acquireLock(
    request: AcquireLockRequest,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: AcquireLockResponse,
    ) => void,
  ): ClientUnaryCall;
  acquireLock(
    request: AcquireLockRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: AcquireLockResponse,
    ) => void,
  ): ClientUnaryCall;
}

export const KesselTupleServiceClient = makeGenericClientConstructor(
  KesselTupleServiceService,
  "kessel.inventory.v1beta2.KesselTupleService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): KesselTupleServiceClient;
  service: typeof KesselTupleServiceService;
  serviceName: string;
};
