// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file kessel/inventory/v1beta2/write_visibility.proto (package kessel.inventory.v1beta2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file kessel/inventory/v1beta2/write_visibility.proto.
 */
export const file_kessel_inventory_v1beta2_write_visibility: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Ci9rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTIvd3JpdGVfdmlzaWJpbGl0eS5wcm90bxIYa2Vzc2VsLmludmVudG9yeS52MWJldGEyKlgKD1dyaXRlVmlzaWJpbGl0eRIgChxXUklURV9WSVNJQklMSVRZX1VOU1BFQ0lGSUVEEAASFAoQTUlOSU1JWkVfTEFURU5DWRABEg0KCUlNTUVESUFURRACQnIKKG9yZy5wcm9qZWN0X2tlc3NlbC5hcGkuaW52ZW50b3J5LnYxYmV0YTJQAVpEZ2l0aHViLmNvbS9wcm9qZWN0LWtlc3NlbC9pbnZlbnRvcnktYXBpL2FwaS9rZXNzZWwvaW52ZW50b3J5L3YxYmV0YTJiBnByb3RvMw",
  );

/**
 * @generated from enum kessel.inventory.v1beta2.WriteVisibility
 */
export enum WriteVisibility {
  /**
   * WRITE_VISIBILITY_UNSPECIFIED: The default behavior of the write operation. Defaults to MINIMIZE_LATENCY
   *   strategy.
   *
   * @generated from enum value: WRITE_VISIBILITY_UNSPECIFIED = 0;
   */
  WRITE_VISIBILITY_UNSPECIFIED = 0,

  /**
   * MINIMIZE_LATENCY: The write operation will be performed with the goal of minimizing latency
   *  by not waiting for data consistency acknowledgment.
   *
   * @generated from enum value: MINIMIZE_LATENCY = 1;
   */
  MINIMIZE_LATENCY = 1,

  /**
   * IMMEDIATE: The write operation will be performed with the goal of ensuring immediate consistency
   *  by waiting for data consistency acknowledgment. Additional
   *  latency may be incurred
   *
   * @generated from enum value: IMMEDIATE = 2;
   */
  IMMEDIATE = 2,
}

/**
 * Describes the enum kessel.inventory.v1beta2.WriteVisibility.
 */
export const WriteVisibilitySchema: GenEnum<WriteVisibility> =
  /*@__PURE__*/
  enumDesc(file_kessel_inventory_v1beta2_write_visibility, 0);
